const assert = require('node:assert/strict');
const snapshot = require('../shared/gear-battle-snapshot.js'); const gear = require('../shared/gear-domain.js'); const combat = require('../shared/gear-combat.js');
let passed = 0; const test = (name, fn) => { fn(); passed++; console.log(`  ok ${name}`); }; const fail = (code, fn) => assert.throws(fn, (error) => error?.code === code);
function empty(characterId = 'kyoryu') { return { characterId, presetId: 'preset1', gearIds: [], slots: { barrel: null, armor: null, core: null, engine: null, sight: null, auxiliary: null } }; }
const context = (characterId = 'kyoryu', baseHp = 100, baseFuel = 50) => ({ expectedCharacterId: characterId, baseHp, baseFuel });
function makeGear(gearId, slotId = 'barrel', setId = 'assault') { return gear.createGear({ gearId, generationSeed: `g:${gearId}`, enhancementSeed: `e:${gearId}`, sourceId: 'coop_boss', sourceDetail: { difficulty: 'normal' }, acquiredAt: '2026-08-26T00:00:00Z', qualityProfile: { id: 'q', starWeights: [{ id: 6, weight: 1 }], rarityWeights: [{ id: 'mythic', weight: 1 }] }, setProfile: { id: 's', setWeights: [{ id: setId, weight: 1 }] }, slotId, setId }); }
function equipped(...items) { const value = empty(); items.forEach((item) => { value.slots[item.slotId] = item; value.gearIds.push(item.gearId); }); return value; }

test('trusted context必須のround trip、freeze、stable bytes、runtime初期値', () => { const value = snapshot.createBattleGearSnapshot({ resolvedLoadout: empty(), baseHp: 100, baseFuel: 50 }); assert.equal(Object.isFrozen(value), true); assert.equal(snapshot.stableSerialize(value, context()), snapshot.stableSerialize(value, context())); assert.deepEqual(value.initialRuntimeState, combat.createRuntimeEffectsState()); fail('INVALID_TRUSTED_BATTLE_CONTEXT', () => snapshot.stableSerialize(value)); });
test('trusted character/baseHp/baseFuelはsnapshot自己申告を正本にしない', () => { const value = snapshot.createBattleGearSnapshot({ resolvedLoadout: empty(), baseHp: 100, baseFuel: 50 }); const char = structuredClone(value); char.characterId = 'other'; fail('INVALID_GEAR_BATTLE_SNAPSHOT', () => snapshot.validateBattleGearSnapshot(char, context())); const hp = structuredClone(value); hp.derivedStats.baseHp = 200; hp.derivedStats = combat.calculateBattleGearCombat({ battleGears: [], baseHp: 200, baseFuel: 50 }); fail('INVALID_GEAR_BATTLE_SNAPSHOT', () => snapshot.validateBattleGearSnapshot(hp, context())); const fuel = structuredClone(value); fuel.derivedStats = combat.calculateBattleGearCombat({ battleGears: [], baseHp: 100, baseFuel: 70 }); fail('INVALID_GEAR_BATTLE_SNAPSHOT', () => snapshot.validateBattleGearSnapshot(fuel, context())); });
test('main/sub/roll metadata/slot/enum/tuning tamperをrejectする', () => { const barrel = gear.enhanceGear(makeGear('barrel'), 3); const armor = makeGear('armor', 'armor'); const value = snapshot.createBattleGearSnapshot({ resolvedLoadout: equipped(barrel, armor), baseHp: 100, baseFuel: 50 }); const main = structuredClone(value); main.slots.barrel.mainOp.value += 1; fail('INVALID_BATTLE_GEAR', () => snapshot.validateBattleGearSnapshot(main, context())); const sub = structuredClone(value); sub.slots.barrel.subs[0].valueBp += 1; fail('INVALID_BATTLE_GEAR', () => snapshot.validateBattleGearSnapshot(sub, context())); const rolls = structuredClone(value); rolls.slots.barrel.subs[0].enhancementRollsBp[0] += 1; fail('INVALID_BATTLE_GEAR', () => snapshot.validateBattleGearSnapshot(rolls, context())); const wrongSlot = structuredClone(value); wrongSlot.slots.barrel.slotId = 'armor'; fail('INVALID_BATTLE_GEAR', () => snapshot.validateBattleGearSnapshot(wrongSlot, context())); for (const [path, changed] of [['star', 7], ['rarityId', 'unknown'], ['setId', 'unknown'], ['enhancementLevel', 13], ['balanceTuningVersion', 999]]) { const copy = structuredClone(value); copy.slots.barrel[path] = changed; fail('INVALID_BATTLE_GEAR', () => snapshot.validateBattleGearSnapshot(copy, context())); } const duplicate = structuredClone(value); duplicate.slots.armor.gearId = duplicate.slots.barrel.gearId; fail('INVALID_BATTLE_GEAR', () => snapshot.validateBattleGearSnapshot(duplicate, context())); });
test('4set conditional capabilityはstatic snapshotへ保持し、active runtime値を焼き込まない', () => { const value = snapshot.createBattleGearSnapshot({ resolvedLoadout: equipped(makeGear('a', 'barrel'), makeGear('b', 'armor'), makeGear('c', 'core'), makeGear('d', 'engine')), baseHp: 100, baseFuel: 50 }); assert.equal(value.derivedStats.conditional.directHitDamageBp, 1200); assert.equal(value.derivedStats.damageReductionBp, 0); const runtime = structuredClone(value); runtime.initialRuntimeState.rescueNextAttackDamageBp = 1000; fail('TAMPERED_GEAR_BATTLE_SNAPSHOT', () => snapshot.validateBattleGearSnapshot(runtime, context())); });
test('resolved IDs/preset exact性とrelevant current stateを照合する', () => { const item = makeGear('same'); const bad = equipped(item); bad.gearIds = []; fail('INVALID_RESOLVED_LOADOUT', () => snapshot.createBattleGearSnapshot({ resolvedLoadout: bad, baseHp: 100, baseFuel: 50 })); const preset = empty(); preset.presetId = 'preset4'; fail('INVALID_RESOLVED_LOADOUT', () => snapshot.createBattleGearSnapshot({ resolvedLoadout: preset, baseHp: 100, baseFuel: 50 })); const first = snapshot.createBattleGearSnapshot({ resolvedLoadout: equipped(item), baseHp: 100, baseFuel: 50 }); const changed = snapshot.createBattleGearSnapshot({ resolvedLoadout: equipped(gear.enhanceGear(item, 3)), baseHp: 100, baseFuel: 50 }); assert.notEqual(snapshot.stableSerialize(first, context()), snapshot.stableSerialize(changed, context())); });
test('seed omissionとtop-level strictness/future versionを維持する', () => { const value = snapshot.createBattleGearSnapshot({ resolvedLoadout: equipped(makeGear('seedless')), baseHp: 100, baseFuel: 50 }); assert.equal('generationSeed' in value.slots.barrel, false); assert.equal('enhancementSeed' in value.slots.barrel, false); const unknown = structuredClone(value); unknown.unknown = true; fail('INVALID_GEAR_BATTLE_SNAPSHOT', () => snapshot.validateBattleGearSnapshot(unknown, context())); const future = structuredClone(value); future.version = 2; fail('UNSUPPORTED_FUTURE_GEAR_BATTLE_SNAPSHOT', () => snapshot.validateBattleGearSnapshot(future, context())); });
console.log(`gear-battle-snapshot: ${passed}/6 passed`);
