const assert = require('node:assert/strict');
const harness = require('./seatharness.js');
const kt = harness.kt(), storage = globalThis.localStorage;
const domain = globalThis.KatamonGearDomain, gearStorage = globalThis.KatamonGearStorage;
const presets = globalThis.KatamonGearPresets, presetStorage = globalThis.KatamonGearPresetStorage;
const combat = globalThis.KatamonGearCombat, rng = globalThis.KatamonGearBattleRng;
let passed = 0; function test(name, fn) { fn(); passed += 1; console.log(`  ok ${name}`); }
function reset() { storage.clear(); storage.gearMutationLockManager = globalThis.navigator.locks; kt.setHasSave(false); kt.setPhase('title'); }
function gear(id, slotId, setId) { for (let i = 0; i < 100; i += 1) { const value = domain.createGear({ gearId: id, generationSeed: `${id}:g:${i}`, enhancementSeed: `${id}:e`, sourceId: 'cpu_battle', sourceDetail: { fixture: '3c2b' }, acquiredAt: '2026-08-26T00:00:00Z', qualityProfile: { id: 'q', starWeights: [{ id: 6, weight: 1 }], rarityWeights: [{ id: 'legend', weight: 1 }] }, setProfile: { id: 's', setWeights: [{ id: setId, weight: 1 }] }, slotId }); if (value) return value; } throw new Error('gear fixture'); }
function install(gears) { const state = gearStorage.createDefaultGearStorageState(); state.inventory = gears.map((entry) => ({ gear: entry, locked: false, favorite: false })); gearStorage.saveGearState(state, storage); let p = presetStorage.load(storage, { characterIds: kt.chars() }); for (const entry of gears) p = presets.setPresetSlot(p, { characterId: 'kyoryu', presetId: 'preset1', slotId: entry.slotId, gearId: entry.gearId, characterIds: kt.chars() }); presetStorage.save(p, storage, { characterIds: kt.chars() }); }
function start(gears = []) { reset(); if (gears.length) install(gears); assert.equal(kt.startBattle('kyoryu'), true); return { snap: kt.cpuBattleGearSnapshotForTest(), crit: kt.cpuGearCritStateForTest() }; }
function projectile(actionOrdinal, directTargetId = 'e1') { return { owner: 'p1', gearDamageProfile: 'normal_cannonball', gearCritActionOrdinal: actionOrdinal, directTargetId, radius: 5, originX: 0, originY: 0 }; }
function hit({ snap, crit }, actionOrdinal, directTargetId = 'e1') { const target = kt.unitById('e1'); const before = target.hp; kt.explodeAtForTest(target.x, target.y, 1, 'p1', true, projectile(actionOrdinal, directTargetId)); return { damage: before - target.hp, roll: rng.rollBasisPoints({ namespace: rng.GEAR_CRIT_RNG_NAMESPACE, version: rng.GEAR_BATTLE_RNG_VERSION, runId: crit.runId, matchOrdinal: crit.matchOrdinal, actionOrdinal, targetUnitId: 'e1', damageType: directTargetId === 'e1' ? 'direct_projectile' : 'normal_blast', hitOrdinal: 0 }) }; }
function blastAt({ snap, crit }, actionOrdinal, distance) { const target = kt.unitById('e1'); const x = target.x - distance; const y = target.y; const before = target.hp; const ground = kt.groundYAt(x); kt.explodeAtForTest(x, y, 1, 'p1', true, projectile(actionOrdinal, 'other')); return { damage: before - target.hp, groundBefore: ground, groundAfter: kt.groundYAt(x) }; }
test('Gearless normal cannonball remains non-crit and existing damage', () => { const state = start(); const result = hit(state, 0); assert.equal(state.snap.derivedStats.critRateBp, 0); assert.equal(result.damage, 45); });
test('normal direct and blast use deterministic Crit labels, while special profile remains excluded', () => { const gears = ['barrel', 'armor', 'sight', 'auxiliary'].map((slot) => gear(`critical-${slot}`, slot, 'critical')); const state = start(gears); const nextCritOrdinal = (source, damageType) => { let ordinal = 0; while (rng.rollBasisPoints({ namespace: rng.GEAR_CRIT_RNG_NAMESPACE, version: rng.GEAR_BATTLE_RNG_VERSION, runId: source.crit.runId, matchOrdinal: source.crit.matchOrdinal, actionOrdinal: ordinal, targetUnitId: 'e1', damageType, hitOrdinal: 0 }) >= source.snap.derivedStats.critRateBp) ordinal += 1; return ordinal; }; const direct = hit(state, nextCritOrdinal(state, 'direct_projectile')); assert.equal(direct.damage, Math.min(kt.unitById('e1').maxHp, Math.round(45 * state.snap.derivedStats.attackMultiplier * state.snap.derivedStats.critDamageMultiplier))); const blastState = start(gears); const blast = hit(blastState, nextCritOrdinal(blastState, 'normal_blast'), 'other'); assert.equal(blast.damage, Math.min(kt.unitById('e1').maxHp, Math.round(45 * blastState.snap.derivedStats.attackMultiplier * blastState.snap.derivedStats.blastDamageMultiplier * blastState.snap.derivedStats.critDamageMultiplier))); start(gears); const specialTarget = kt.unitById('e1'); const before = specialTarget.hp; kt.explodeAtForTest(specialTarget.x, specialTarget.y, 1, 'p1', true, { gearDamageProfile: 'excluded', directTargetId: 'e1', radius: 5 }); assert.equal(before - specialTarget.hp, 45); });
test('Blast Power affects only normal blast damage/reach and never terrain', () => { const gears = ['barrel', 'armor', 'sight', 'auxiliary'].map((slot) => gear(`blast-${slot}`, slot, 'blast')); const state = start(gears); const target = kt.unitById('e1'); const ground = kt.groundYAt(target.x); const blast = hit(state, 0, 'other'); assert(blast.damage > 45, 'blast2/4 must raise normal blast damage'); assert.equal(kt.groundYAt(target.x), ground); });
test('Crit runtime identity is match-fixed and advances only on normal cannonball launch', () => { const state = start(); kt.fireForTest(120, -40, { unitId: 'p1' }); assert.equal(kt.cpuGearCritStateForTest().nextActionOrdinal, state.crit.nextActionOrdinal + 1); assert.equal(kt.saveCpuBattleAtTurnStartForTest(), true); const saved = kt.buildSnapshotForTest(); assert.equal(saved.cpuGearCritStateVersion, 1); assert.deepEqual(saved.cpuGearCritState, kt.cpuGearCritStateForTest()); });
test('Blast range extends only normal blast damage reach, never terrain reach', () => { const none = blastAt(start(), 0, 105); assert.equal(none.damage, 0); const gears = ['barrel', 'armor', 'sight', 'auxiliary'].map((slot) => gear(`blast-range-${slot}`, slot, 'blast')); const boosted = blastAt(start(gears), 0, 105); assert(boosted.damage > 0); assert.equal(boosted.groundAfter, boosted.groundBefore); });
test('Crit resume preserves the next label, while legacy absence is allowed and malformed current state fails closed', () => { const gears = ['barrel', 'armor', 'sight', 'auxiliary'].map((slot) => gear(`crit-resume-${slot}`, slot, 'critical')); const state = start(gears); kt.fireForTest(120, -40, { unitId: 'p1' }); const before = kt.cpuGearCritStateForTest(); const expected = rng.rollBasisPoints({ namespace: rng.GEAR_CRIT_RNG_NAMESPACE, version: rng.GEAR_BATTLE_RNG_VERSION, runId: before.runId, matchOrdinal: before.matchOrdinal, actionOrdinal: before.nextActionOrdinal, targetUnitId: 'e1', damageType: 'direct_projectile', hitOrdinal: 0 }); assert.equal(kt.saveCpuBattleAtTurnStartForTest(), true); gearStorage.saveGearState(gearStorage.createDefaultGearStorageState(), storage); kt.setPhase('title'); assert.equal(kt.resumeCpuSuspendForTest(), true); const restored = kt.cpuGearCritStateForTest(); assert.deepEqual(restored, before); assert.equal(rng.rollBasisPoints({ namespace: rng.GEAR_CRIT_RNG_NAMESPACE, version: rng.GEAR_BATTLE_RNG_VERSION, runId: restored.runId, matchOrdinal: restored.matchOrdinal, actionOrdinal: restored.nextActionOrdinal, targetUnitId: 'e1', damageType: 'direct_projectile', hitOrdinal: 0 }), expected); reset(); assert.equal(kt.startBattle('kyoryu'), true); assert.equal(kt.saveCpuBattleAtTurnStartForTest(), true); const legacy = JSON.parse(storage.getItem('katamon_suspend_v1')); delete legacy.cpuGearCritStateVersion; delete legacy.cpuGearCritState; storage.setItem('katamon_suspend_v1', JSON.stringify(legacy)); kt.setPhase('title'); assert.equal(kt.resumeCpuSuspendForTest(), true); assert.equal(kt.cpuGearCritStateForTest().nextActionOrdinal, 0); assert.equal(kt.saveCpuBattleAtTurnStartForTest(), true); const malformed = JSON.parse(storage.getItem('katamon_suspend_v1')); malformed.cpuGearCritState.nextActionOrdinal = -1; storage.setItem('katamon_suspend_v1', JSON.stringify(malformed)); kt.setPhase('title'); assert.equal(kt.resumeCpuSuspendForTest(), false); });
test('self blast is never a Crit, and the next CPU match has a new Crit identity', () => { const gears = ['barrel', 'armor', 'sight', 'auxiliary'].map((slot) => gear(`crit-self-${slot}`, slot, 'critical')); const state = start(gears); const player = kt.unitById('p1'); const before = player.hp; kt.explodeAtForTest(player.x, player.y, 1, 'p1', true, projectile(0, 'p1')); const nonCrit = Math.round(combat.calculateDamagePipeline({ baseDamage: 45, attackMultiplier: state.snap.derivedStats.attackMultiplier, modifierBp: 0, isCrit: false, critDamageMultiplier: state.snap.derivedStats.critDamageMultiplier, defenseMultiplier: state.snap.derivedStats.defenseMultiplier, damageReductionBp: 0, numericShield: 0 }).hpDamage); assert.equal(before - player.hp, nonCrit); const first = kt.cpuGearCritStateForTest(); kt.setWinStreakForTest(1); assert.equal(kt.continueCpuGearRunAfterWinForTest(), true); const next = kt.cpuGearCritStateForTest(); assert.equal(next.runId, first.runId); assert.equal(next.matchOrdinal, 1); assert.notEqual(rng.rollBasisPoints({ namespace: rng.GEAR_CRIT_RNG_NAMESPACE, version: rng.GEAR_BATTLE_RNG_VERSION, runId: first.runId, matchOrdinal: first.matchOrdinal, actionOrdinal: 0, targetUnitId: 'e1', damageType: 'direct_projectile', hitOrdinal: 0 }), rng.rollBasisPoints({ namespace: rng.GEAR_CRIT_RNG_NAMESPACE, version: rng.GEAR_BATTLE_RNG_VERSION, runId: next.runId, matchOrdinal: next.matchOrdinal, actionOrdinal: 0, targetUnitId: 'e1', damageType: 'direct_projectile', hitOrdinal: 0 })); });
test('ownerless snapshots with a current Crit field fail closed instead of rebinding its durable label', () => { start(); assert.equal(kt.saveCpuBattleAtTurnStartForTest(), true); const forged = JSON.parse(storage.getItem('katamon_suspend_v1')); delete forged.cpuGearOwnerSessionId; delete forged.cpuGearSnapshotId; storage.setItem('katamon_suspend_v1', JSON.stringify(forged)); assert.equal(kt.clearCpuGearRunForTest(), true); kt.setPhase('title'); assert.equal(kt.resumeCpuSuspendForTest(), false); });
console.log(`gear-battle-crit-blast-phase3c2b: ${passed}/${passed} passed`);
