const assert = require('node:assert/strict');
const harness = require('./seatharness.js');
const kt = harness.kt(); const storage = globalThis.localStorage;
const domain = globalThis.KatamonGearDomain; const gearStorage = globalThis.KatamonGearStorage;
const presets = globalThis.KatamonGearPresets; const presetStorage = globalThis.KatamonGearPresetStorage;
const combat = globalThis.KatamonGearCombat; const rng = globalThis.KatamonGearBattleRng;
let passed = 0; function test(name, fn) { fn(); passed += 1; console.log(`  ok ${name}`); }
function reset() { storage.clear(); storage.gearMutationLockManager = globalThis.navigator.locks; kt.setHasSave(false); kt.setPhase('title'); }
function statusGear() { for (let attempt = 0; attempt < 200; attempt += 1) { const gear = domain.createGear({ gearId: `status-aux:${attempt}`, generationSeed: `status-aux:${attempt}`, enhancementSeed: 'status-enhancement', sourceId: 'cpu_battle', sourceDetail: { fixture: 'phase3c3b' }, acquiredAt: '2026-08-26T00:00:00Z', qualityProfile: { id: 'phase3c3b', starWeights: [{ id: 6, weight: 1 }], rarityWeights: [{ id: 'legend', weight: 1 }] }, setProfile: { id: 'phase3c3b', setWeights: [{ id: 'assault', weight: 1 }] }, slotId: 'auxiliary' }); if (gear.mainOp.opId === 'status_resistance' || gear.subOps.some((sub) => sub.opId === 'status_resistance')) return gear; } throw new Error('could not make status resistance fixture'); }
function installStatusGear() { const gear = statusGear(); const state = gearStorage.createDefaultGearStorageState(); state.inventory = [{ gear, locked: false, favorite: false }]; gearStorage.saveGearState(state, storage); let preset = presetStorage.load(storage, { characterIds: kt.chars() }); preset = presets.setPresetSlot(preset, { characterId: 'kyoryu', presetId: 'preset1', slotId: 'auxiliary', gearId: gear.gearId, characterIds: kt.chars() }); presetStorage.save(preset, storage, { characterIds: kt.chars() }); }
function start(withStatusGear = false) { reset(); if (withStatusGear) installStatusGear(); assert.equal(kt.startBattle('kyoryu'), true); return kt.cpuBattleGearSnapshotForTest(); }
function ordinalFor(snapshot, predicate, statusId = 'move_lock') { const state = kt.cpuGearStatusStateForTest(); for (let actionOrdinal = 0; actionOrdinal < 10000; actionOrdinal += 1) { const rollBp = rng.rollStatusBasisPoints({ namespace: rng.GEAR_STATUS_RNG_NAMESPACE, version: rng.GEAR_BATTLE_RNG_VERSION, runId: state.runId, matchOrdinal: state.matchOrdinal, actionOrdinal, sourceUnitId: 'e1', targetUnitId: 'p1', statusId, hitOrdinal: 0 }); if (predicate(rollBp, combat.statusSuccessChance(10000, snapshot.derivedStats.statusResistanceBp))) return actionOrdinal; } throw new Error('no status roll fixture found'); }

test('Gearless hostile EMP retains certain legacy status and damage', () => { start(false); const p1 = kt.unitById('p1'); const before = p1.hp; kt.emitEmpForTest(p1.x, p1.y, 100, 'e1', 2, 0); assert.equal(before - p1.hp, 20); assert.equal(kt.turnEffectForTest('p1').moveLockTurns, 2); });
test('EMP uses snapshot Status Resistance and leaves damage intact', () => { const snapshot = start(true); assert(snapshot.derivedStats.statusResistanceBp > 0); const chance = combat.statusSuccessChance(10000, snapshot.derivedStats.statusResistanceBp); const resistOrdinal = ordinalFor(snapshot, (roll) => roll >= chance); const p1 = kt.unitById('p1'); const before = p1.hp; kt.emitEmpForTest(p1.x, p1.y, 100, 'e1', 2, resistOrdinal); assert.equal(before - p1.hp, 20); assert.equal(kt.turnEffectForTest('p1').moveLockTurns, 0); });
test('deterministic Status labels can produce successful EMP independently', () => { const snapshot = start(true); const chance = combat.statusSuccessChance(10000, snapshot.derivedStats.statusResistanceBp); const successOrdinal = ordinalFor(snapshot, (roll) => roll < chance); const p1 = kt.unitById('p1'); kt.emitEmpForTest(p1.x, p1.y, 100, 'e1', 2, successOrdinal); assert.equal(kt.turnEffectForTest('p1').moveLockTurns, 2); });
test('human-to-CPU EMP retains legacy status behavior', () => { start(true); const e1 = kt.unitById('e1'); kt.emitEmpForTest(e1.x, e1.y, 100, 'p1', 2, 0); assert.equal(kt.turnEffectForTest('e1').moveLockTurns, 2); });
test('Status action ordinals are independent from Crit and advance once per EMP', () => { start(true); const critBefore = kt.cpuGearCritStateForTest(); assert.equal(kt.fireEmpForTest('e1'), 0); assert.equal(kt.cpuGearStatusStateForTest().nextActionOrdinal, 1); assert.deepEqual(kt.cpuGearCritStateForTest(), critBefore); });
test('one generated multi-projectile EMP action shares one Status ordinal', () => { start(true); const ordinals = kt.launchGeneratedEmpForTest('e1', 3); assert.deepEqual(ordinals, [0, 0, 0]); assert.equal(kt.cpuGearStatusStateForTest().nextActionOrdinal, 1); });
test('Status state survives official suspend with fixed Gear snapshot', () => { const snapshot = start(true); assert.equal(kt.fireEmpForTest('e1'), 0); assert.equal(kt.saveCpuBattleAtTurnStartForTest(), true); kt.setPhase('title'); assert.equal(kt.resumeCpuSuspendForTest(), true, kt.cpuGearPersistenceForTest().status); assert.equal(kt.cpuGearStatusStateForTest().nextActionOrdinal, 1); assert.equal(kt.cpuBattleGearSnapshotForTest().derivedStats.statusResistanceBp, snapshot.derivedStats.statusResistanceBp); });
test('the next Status roll and result are identical across official suspend/resume', () => { const snapshot = start(true); assert.equal(kt.fireEmpForTest('e1'), 0); const before = kt.cpuGearStatusStateForTest(); const label = (state) => rng.rollStatusBasisPoints({ namespace: rng.GEAR_STATUS_RNG_NAMESPACE, version: rng.GEAR_BATTLE_RNG_VERSION, runId: state.runId, matchOrdinal: state.matchOrdinal, actionOrdinal: state.nextActionOrdinal, sourceUnitId: 'e1', targetUnitId: 'p1', statusId: 'move_lock', hitOrdinal: 0 }); const expectedRoll = label(before); const expectedResult = expectedRoll < combat.statusSuccessChance(10000, snapshot.derivedStats.statusResistanceBp); assert.equal(kt.saveCpuBattleAtTurnStartForTest(), true); kt.setPhase('title'); assert.equal(kt.resumeCpuSuspendForTest(), true); const restored = kt.cpuGearStatusStateForTest(); assert.equal(label(restored), expectedRoll); assert.equal(label(restored) < combat.statusSuccessChance(10000, kt.cpuBattleGearSnapshotForTest().derivedStats.statusResistanceBp), expectedResult); });
test('the next CPU match resets the Status ordinal under a new match identity', () => { start(true); const first = kt.cpuGearStatusStateForTest(); assert.equal(kt.fireEmpForTest('e1'), 0); kt.setWinStreakForTest(1); assert.equal(kt.continueCpuGearRunAfterWinForTest(), true); const next = kt.cpuGearStatusStateForTest(); assert.equal(next.runId, first.runId); assert.equal(next.matchOrdinal, first.matchOrdinal + 1); assert.equal(next.nextActionOrdinal, 0); const roll = (state) => rng.rollStatusBasisPoints({ namespace: rng.GEAR_STATUS_RNG_NAMESPACE, version: rng.GEAR_BATTLE_RNG_VERSION, runId: state.runId, matchOrdinal: state.matchOrdinal, actionOrdinal: 0, sourceUnitId: 'e1', targetUnitId: 'p1', statusId: 'move_lock', hitOrdinal: 0 }); assert.notEqual(roll(first), roll(next)); });
test('legacy missing state resumes but malformed current Status state fails closed', () => { start(true); assert.equal(kt.saveCpuBattleAtTurnStartForTest(), true); const raw = JSON.parse(storage.getItem('katamon_suspend_v1')); delete raw.cpuGearStatusState; delete raw.cpuGearStatusStateVersion; storage.setItem('katamon_suspend_v1', JSON.stringify(raw)); kt.setPhase('title'); assert.equal(kt.resumeCpuSuspendForTest(), true); assert.equal(kt.cpuGearStatusStateForTest().nextActionOrdinal, 0); assert.equal(kt.saveCpuBattleAtTurnStartForTest(), true); const malformed = JSON.parse(storage.getItem('katamon_suspend_v1')); malformed.cpuGearStatusState.nextActionOrdinal = -1; storage.setItem('katamon_suspend_v1', JSON.stringify(malformed)); kt.setPhase('title'); assert.equal(kt.resumeCpuSuspendForTest(), false); });
test('partial, ownerless, and snapshot-less current Status state fail closed', () => { start(true); assert.equal(kt.saveCpuBattleAtTurnStartForTest(), true); const partial = JSON.parse(storage.getItem('katamon_suspend_v1')); delete partial.cpuGearStatusStateVersion; storage.setItem('katamon_suspend_v1', JSON.stringify(partial)); kt.setPhase('title'); assert.equal(kt.resumeCpuSuspendForTest(), false); start(true); assert.equal(kt.saveCpuBattleAtTurnStartForTest(), true); const missingSnapshot = JSON.parse(storage.getItem('katamon_suspend_v1')); delete missingSnapshot.cpuBattleGearSnapshotVersion; delete missingSnapshot.cpuBattleGearSnapshot; storage.setItem('katamon_suspend_v1', JSON.stringify(missingSnapshot)); kt.setPhase('title'); assert.equal(kt.resumeCpuSuspendForTest(), false); });
test('current Status state rejects run/match/version and unknown-shape tampering', () => { const mutateAndReject = (mutate) => { start(true); assert.equal(kt.saveCpuBattleAtTurnStartForTest(), true); const raw = JSON.parse(storage.getItem('katamon_suspend_v1')); mutate(raw.cpuGearStatusState); storage.setItem('katamon_suspend_v1', JSON.stringify(raw)); kt.setPhase('title'); assert.equal(kt.resumeCpuSuspendForTest(), false); }; mutateAndReject((state) => { state.runId = 'other-run'; }); mutateAndReject((state) => { state.matchOrdinal += 1; }); mutateAndReject((state) => { state.version = 2; }); mutateAndReject((state) => { state.extra = true; }); });
test('hostile EMP with a missing current action ordinal fails closed, while action-skip uses the same resistance gate', () => { const snapshot = start(true); const p1 = kt.unitById('p1'); assert.throws(() => kt.emitEmpForTest(p1.x, p1.y, 100, 'e1', 2), /CPU_GEAR_STATUS_ACTION_MALFORMED/); const chance = combat.statusSuccessChance(10000, snapshot.derivedStats.statusResistanceBp); const resistOrdinal = ordinalFor(snapshot, (roll) => roll >= chance, 'action_skip'); kt.emitNyanDisableForTest(p1.x, p1.y, 100, 'e1', resistOrdinal); assert.equal(kt.turnEffectForTest('p1').actionSkipTurns, 0); });
test('Status adds no Math.random calls and ONLINE remains outside the gate', () => { const calls = (withGear) => { start(withGear); const p1 = kt.unitById('p1'); const old = Math.random; let count = 0; Math.random = () => { count += 1; return 0.5; }; try { kt.emitEmpForTest(p1.x, p1.y, 100, 'e1', 2, 0); return count; } finally { Math.random = old; } }; assert.equal(calls(true), calls(false)); start(true); const p1 = kt.unitById('p1'); kt.setOnlineForCpuGearEligibilityForTest({ kind: 'firebase' }); kt.emitEmpForTest(p1.x, p1.y, 100, 'e1', 2, 0); assert.equal(kt.turnEffectForTest('p1').moveLockTurns, 2); });
console.log(`gear-battle-status-phase3c3b: ${passed}/${passed} passed`);
