const assert = require('node:assert/strict');
const combat = require('../shared/gear-combat.js');
let passed = 0; const test = (name, fn) => { fn(); passed++; console.log(`  ok ${name}`); };
const gear = (setId) => ({ slotId: 'engine', setId, mainOp: { opId: 'attack_pct', value: 0 }, subs: [] });
const combatFor = (setId, count) => combat.calculateBattleGearCombat({ battleGears: Array.from({ length: count }, () => gear(setId)), baseHp: 100, baseFuel: 10 });
const rescue = combatFor('rescue', 4); const last = combatFor('last_stand', 4); const plain = combatFor('life', 2);

test('rescueはsource→targetだけにrefreshし、結果は今回event基準でtruthful', () => { let value = combat.recordSupportEvent({ sourceCombat: rescue, targetCombat: last, sourceUnitId: 'A', targetUnitId: 'B', actualHealing: 1 }); assert.equal(value.didGrant, true); assert.equal(value.grantedNextAttackDamageBp, rescue.conditional.rescueNextAttackDamageBp); const stale = combat.recordSupportEvent({ sourceCombat: rescue, targetCombat: last, targetState: value.state, sourceUnitId: 'A', targetUnitId: 'A', actualHealing: 1 }); assert.equal(stale.state.rescueNextAttackDamageBp, rescue.conditional.rescueNextAttackDamageBp); assert.equal(stale.didGrant, false); assert.equal(stale.grantedNextAttackDamageBp, 0); const none = combat.recordSupportEvent({ sourceCombat: plain, targetCombat: last, targetState: value.state, sourceUnitId: 'A', targetUnitId: 'B', actualHealing: 1 }); assert.equal(none.didGrant, false); assert.equal(none.grantedNextAttackDamageBp, 0); });
test('last standは50%を再評価し、+10% Attackと+10/+15% next actionを分離する', () => { assert.equal(combat.resolveRuntimeEffects({ combat: last, currentHp: 51 }).runtimeAttackPctBp, 0); assert.equal(combat.resolveRuntimeEffects({ combat: last, currentHp: 50 }).runtimeAttackPctBp, last.conditional.lastStandLowHpAttackBp); assert.equal(combat.resolveRuntimeEffects({ combat: last, currentHp: 50, actualEnemyDamage: 1, damageType: 'normal_blast' }).nextAttackDamageBp, last.conditional.lastStandLowHpNextAttackDamageBp); assert.equal(combat.resolveRuntimeEffects({ combat: last, currentHp: 51, actualEnemyDamage: 1, damageType: 'direct_projectile' }).nextAttackDamageBp, last.conditional.lastStandNextAttackDamageBp); for (const type of ['status', 'environmental', 'self', 'fixed']) assert.equal(combat.resolveRuntimeEffects({ combat: last, currentHp: 50, actualEnemyDamage: 1, damageType: type }).nextAttackDamageBp, 0); });
test('runtime値域とcombat capabilityはGearDomain由来canonical値だけを受理する', () => { for (const state of [{ rescueNextAttackDamageBp: 999999, lastStandNextAttackDamageBp: 0 }, { rescueNextAttackDamageBp: 500, lastStandNextAttackDamageBp: 0 }, { rescueNextAttackDamageBp: 0, lastStandNextAttackDamageBp: 1234 }]) assert.throws(() => combat.beginAttackAction({ combat: last, state }), (error) => error?.code === 'INVALID_RUNTIME_EFFECTS_STATE'); assert.throws(() => combat.beginAttackAction({ combat: plain, state: { rescueNextAttackDamageBp: 0, lastStandNextAttackDamageBp: last.conditional.lastStandLowHpNextAttackDamageBp } }), (error) => error?.code === 'INVALID_RUNTIME_EFFECTS_STATE'); assert.equal(combat.beginAttackAction({ combat: last, state: { rescueNextAttackDamageBp: rescue.conditional.rescueNextAttackDamageBp, lastStandNextAttackDamageBp: last.conditional.lastStandLowHpNextAttackDamageBp } }).actionDamageBp, 2500); });
test('next-action buffはaction全体で維持し、completeで一回だけ消費する', () => { let state = combat.resolveRuntimeEffects({ combat: last, currentHp: 50, actualEnemyDamage: 1, damageType: 'direct_projectile' }).state; state = combat.recordSupportEvent({ sourceCombat: rescue, targetCombat: last, targetState: state, sourceUnitId: 'A', targetUnitId: 'B', actualHealing: 1 }).state; const action = combat.beginAttackAction({ combat: last, state }); assert.equal(action.actionDamageBp, 2500); assert.equal(combat.beginAttackAction({ combat: last, state: action.state }).actionDamageBp, 2500); assert.equal(combat.beginAttackAction({ combat: last, state: combat.completeAttackAction({ combat: last, state: action.state }) }).actionDamageBp, 0); });
test('life shieldは両倍率後に35% cap、unknown damage typeはfail closed', () => { const life = { ...combatFor('life', 4), shieldMultiplier: 1.2, receivedShieldMultiplier: 1.1 }; assert(Math.abs(combat.initialShieldFromSets(life).gained - 11.616) < 1e-9); assert.throws(() => combat.resolveRuntimeEffects({ combat: last, currentHp: 50, actualEnemyDamage: 1, damageType: 'unknown' }), (error) => error?.code === 'INVALID_DAMAGE_TYPE'); });
console.log(`gear-combat-runtime-effects: ${passed}/5 passed`);
