const assert = require('node:assert/strict');
const harness = require('./seatharness.js');
globalThis.KatamonSubweapons = require('../subweapon-mvp.js');
const kt = harness.kt();
const storage = globalThis.localStorage;
const domain = globalThis.KatamonGearDomain;
const gearStorage = globalThis.KatamonGearStorage;
const presets = globalThis.KatamonGearPresets;
const presetStorage = globalThis.KatamonGearPresetStorage;
const combat = globalThis.KatamonGearCombat;
let passed = 0; const test = (name, fn) => { fn(); passed += 1; console.log(`  ok ${name}`); };
function reset() { storage.clear(); storage.gearMutationLockManager = globalThis.navigator.locks; kt.setHasSave(false); kt.setOnlineForCpuGearEligibilityForTest(null); kt.setPhase('title'); }
function gear(id, slotId) { return domain.createGear({ gearId: id, generationSeed: `${id}:g`, enhancementSeed: `${id}:e`, sourceId: 'cpu_battle', sourceDetail: { fixture: 'phase3c3d' }, acquiredAt: '2026-08-27T00:00:00Z', qualityProfile: { id: 'phase3c3d', starWeights: [{ id: 6, weight: 1 }], rarityWeights: [{ id: 'legend', weight: 1 }] }, setProfile: { id: 'phase3c3d', setWeights: [{ id: 'last_stand', weight: 1 }] }, slotId }); }
function start(count = 4) { reset(); const gears = ['barrel', 'armor', 'core', 'engine'].slice(0, count).map((slot) => gear(`last-${slot}`, slot)); const state = gearStorage.createDefaultGearStorageState(); state.inventory = gears.map((value) => ({ gear: value, locked: false, favorite: false })); gearStorage.saveGearState(state, storage); let preset = presetStorage.load(storage, { characterIds: kt.chars() }); for (const value of gears) preset = presets.setPresetSlot(preset, { characterId: 'kyoryu', presetId: 'preset1', slotId: value.slotId, gearId: value.gearId, characterIds: kt.chars() }); presetStorage.save(preset, storage, { characterIds: kt.chars() }); assert.equal(kt.startBattle('kyoryu'), true); return kt.cpuBattleGearSnapshotForTest(); }
function effects() { return kt.cpuGearRuntimeEffectsStateForTest().effects; }

test('fresh CPU match keeps rescue at zero and starts Last Stand runtime at zero', () => { start(); assert.deepEqual(effects(), combat.createRuntimeEffectsState()); });
test('Last Stand 2pc captures the exact 50% Attack bucket at action start only', () => { const snapshot = start(2); const p1 = kt.unitById('p1'); kt.setUnitHpForTest('p1', p1.maxHp / 2); const active = kt.beginCpuGearAttackForTest(); assert.equal(active.attackMultiplier, combat.resolveAttackMultiplier({ combat: snapshot.derivedStats, runtimeAttackPctBp: snapshot.derivedStats.conditional.lastStandLowHpAttackBp })); kt.setUnitHpForTest('p1', p1.maxHp); assert.equal(kt.beginCpuGearAttackForTest().attackMultiplier, active.attackMultiplier); kt.completeCpuGearAttackForTest(); assert.equal(kt.beginCpuGearAttackForTest().attackMultiplier, snapshot.derivedStats.attackMultiplier); });
test('enemy attack actual HP damage overwrites +10 with post-hit +15 instead of stacking', () => { const snapshot = start(); const p1 = kt.unitById('p1'); kt.setUnitHpForTest('p1', p1.maxHp * .6); kt.recordCpuGearLastStandDamageForTest('e1', 1); assert.equal(effects().lastStandNextAttackDamageBp, snapshot.derivedStats.conditional.lastStandNextAttackDamageBp); kt.setUnitHpForTest('p1', p1.maxHp * .5); kt.recordCpuGearLastStandDamageForTest('e1', 1); assert.equal(effects().lastStandNextAttackDamageBp, snapshot.derivedStats.conditional.lastStandLowHpNextAttackDamageBp); });
test('shield/full-zero damage, DoT and non-enemy actions never grant Last Stand', () => { start(); kt.recordCpuGearLastStandDamageForTest('e1', 0); kt.recordCpuGearLastStandDamageForTest('e1', 3, 'environmental', false); kt.recordCpuGearLastStandDamageForTest('p1', 3); assert.equal(effects().lastStandNextAttackDamageBp, 0); });
test('stored Last Stand is a Damage Modifier, coexists with Last Stand 2, and consumes only after the action', () => { const snapshot = start(); const p1 = kt.unitById('p1'); kt.setUnitHpForTest('p1', p1.maxHp * .5); const bonus = snapshot.derivedStats.conditional.lastStandLowHpNextAttackDamageBp; assert(kt.setCpuGearRuntimeEffectsForTest({ rescueNextAttackDamageBp: 0, lastStandNextAttackDamageBp: bonus })); const active = kt.beginCpuGearAttackForTest(); assert.equal(active.actionDamageBp, bonus); assert.equal(active.attackMultiplier, combat.resolveAttackMultiplier({ combat: snapshot.derivedStats, runtimeAttackPctBp: snapshot.derivedStats.conditional.lastStandLowHpAttackBp })); assert.equal(effects().lastStandNextAttackDamageBp, bonus); kt.completeCpuGearAttackForTest(); assert.equal(effects().lastStandNextAttackDamageBp, 0); });
test('official suspend keeps stored buff, while legacy missing state resumes as zero', () => { const snapshot = start(); const bonus = snapshot.derivedStats.conditional.lastStandNextAttackDamageBp; kt.setCpuGearRuntimeEffectsForTest({ rescueNextAttackDamageBp: 0, lastStandNextAttackDamageBp: bonus }); assert.equal(kt.saveCpuBattleAtTurnStartForTest(), true); kt.setPhase('title'); assert.equal(kt.resumeCpuSuspendForTest(), true); assert.equal(effects().lastStandNextAttackDamageBp, bonus); assert.equal(kt.saveCpuBattleAtTurnStartForTest(), true); const legacy = JSON.parse(storage.getItem('katamon_suspend_v1')); delete legacy.cpuGearRuntimeEffectsState; delete legacy.cpuGearRuntimeEffectsStateVersion; storage.setItem('katamon_suspend_v1', JSON.stringify(legacy)); kt.setPhase('title'); assert.equal(kt.resumeCpuSuspendForTest(), true); assert.equal(effects().lastStandNextAttackDamageBp, 0); });
test('malformed current runtime state and nonzero rescue fail closed', () => { const reject = (mutate) => { start(); assert.equal(kt.saveCpuBattleAtTurnStartForTest(), true); const raw = JSON.parse(storage.getItem('katamon_suspend_v1')); mutate(raw); storage.setItem('katamon_suspend_v1', JSON.stringify(raw)); kt.setPhase('title'); assert.equal(kt.resumeCpuSuspendForTest(), false); }; reject((raw) => { raw.cpuGearRuntimeEffectsState.effects.rescueNextAttackDamageBp = 1000; }); reject((raw) => { raw.cpuGearRuntimeEffectsState.runId = 'other'; }); reject((raw) => { raw.cpuGearRuntimeEffectsState.effects.lastStandNextAttackDamageBp = 1234; }); });
test('fresh next CPU match has no carried Last Stand and ONLINE remains inert', () => { const snapshot = start(); kt.setCpuGearRuntimeEffectsForTest({ rescueNextAttackDamageBp: 0, lastStandNextAttackDamageBp: snapshot.derivedStats.conditional.lastStandNextAttackDamageBp }); kt.setWinStreakForTest(1); assert.equal(kt.continueCpuGearRunAfterWinForTest(), true); assert.equal(effects().lastStandNextAttackDamageBp, 0); kt.setOnlineForCpuGearEligibilityForTest({ kind: 'firebase' }); assert.equal(kt.beginCpuGearAttackForTest(), null); });
test('Last Stand 4 applies once to EMP and firework immediate damage without changing Status state', () => { const snapshot = start(); const bonus = snapshot.derivedStats.conditional.lastStandLowHpNextAttackDamageBp; const e1 = kt.unitById('e1'); const statusBefore = kt.cpuGearStatusStateForTest(); assert(kt.setCpuGearRuntimeEffectsForTest({ rescueNextAttackDamageBp: 0, lastStandNextAttackDamageBp: bonus })); kt.beginCpuGearAttackForTest(); let before = e1.hp; kt.emitEmpForTest(e1.x, e1.y, 100, 'p1', 1); assert.equal(before - e1.hp, 23); assert.deepEqual(kt.cpuGearStatusStateForTest(), statusBefore); kt.completeCpuGearAttackForTest(); assert.equal(effects().lastStandNextAttackDamageBp, 0); assert(kt.setCpuGearRuntimeEffectsForTest({ rescueNextAttackDamageBp: 0, lastStandNextAttackDamageBp: bonus })); kt.beginCpuGearAttackForTest(); before = e1.hp; kt.fireworkShardExplodeForTest(e1.x, e1.y, 'p1'); assert.equal(before - e1.hp, 9); assert.equal(effects().lastStandNextAttackDamageBp, bonus); kt.completeCpuGearAttackForTest(); });
test('Impact and Drill receive/consume the stored modifier as offensive actions while Barrier preserves it', () => { const snapshot = start(); const bonus = snapshot.derivedStats.conditional.lastStandNextAttackDamageBp; const e1 = kt.unitById('e1'); assert(kt.setCpuGearRuntimeEffectsForTest({ rescueNextAttackDamageBp: 0, lastStandNextAttackDamageBp: bonus })); const barrier = kt.launchSubweaponForTest('p1', 'barrier'); assert.equal(barrier.active, null); assert.equal(effects().lastStandNextAttackDamageBp, bonus); const impact = kt.launchSubweaponForTest('p1', 'impact'); assert.equal(impact.active.actionDamageBp, bonus); const impactBefore = e1.hp; kt.detonateProjectileForTest(impact.projectileIndex, e1.x, e1.y); assert.equal(impactBefore - e1.hp, 28); kt.completeCpuGearAttackForTest(); assert.equal(effects().lastStandNextAttackDamageBp, 0); assert(kt.setCpuGearRuntimeEffectsForTest({ rescueNextAttackDamageBp: 0, lastStandNextAttackDamageBp: bonus })); const drill = kt.launchSubweaponForTest('p1', 'drill'); assert.equal(drill.active.actionDamageBp, bonus); const drillBefore = e1.hp; kt.detonateProjectileForTest(drill.projectileIndex, e1.x, e1.y); assert.equal(drillBefore - e1.hp, 17); kt.completeCpuGearAttackForTest(); assert.equal(effects().lastStandNextAttackDamageBp, 0); });
console.log(`gear-battle-last-stand-phase3c3d: ${passed}/${passed} passed`);
