const assert = require('node:assert/strict');
const combat = require('../shared/gear-combat.js'); const domain = require('../shared/gear-domain.js');
let passed = 0; const test = (name, fn) => { fn(); passed++; console.log(`  ok ${name}`); };
const gear = (slotId, mainOp, value, setId = 'assault', subs = []) => ({ slotId, setId, mainOp: { opId: mainOp, value }, subs });
const setLoadout = (setId, count, main = 'attack_pct') => Array.from({ length: count }, () => gear('engine', main, 0, setId));

test('Gearなしは完全identity', () => { const value = combat.calculateGearCombat({ loadout: [], baseHp: 100, baseFuel: 50 }); assert.equal(value.attackMultiplier, 1); assert.equal(value.defenseMultiplier, 1); assert.equal(value.maxHp, 100); assert.equal(value.critRateBp, 0); assert.equal(value.critDamageBp, 15000); assert.equal(value.blastPowerBp, 0); assert.equal(value.maxFuel, 50); assert.deepEqual(combat.createRuntimeEffectsState(), { rescueNextAttackDamageBp: 0, lastStandNextAttackDamageBp: 0 }); });
test('normalized Attack/Defense/HPと背水2setは同じAttack bucketで一回だけ解決する', () => { const value = combat.calculateBattleGearCombat({ battleGears: [gear('barrel', 'flat_attack', 12, 'last_stand'), gear('engine', 'attack_pct', 2000, 'last_stand')], baseHp: 100, baseFuel: 50 }); assert.equal(value.attackMultiplier, 1.344); assert.equal(combat.resolveAttackMultiplier({ combat: value, runtimeAttackPctBp: value.conditional.lastStandLowHpAttackBp }), 1.456); assert.notEqual(combat.resolveAttackMultiplier({ combat: value, runtimeAttackPctBp: 1000 }), value.attackMultiplier * 1.1); });
test('Defense boundaryとdamage classifierは承認式どおり', () => { const calc = (items) => combat.calculateBattleGearCombat({ battleGears: items, baseHp: 100, baseFuel: 10 }).defenseMultiplier; assert.equal(calc([]), 1); assert.equal(calc([gear('core', 'flat_defense', 20)]), 100 / 110); assert.equal(calc([gear('core', 'flat_defense', 50)]), .8); assert.equal(combat.isCritEligibleDamageType('direct_projectile'), true); assert.equal(combat.isCritEligibleDamageType('status'), false); assert.throws(() => combat.isCritEligibleDamageType('unknown'), (error) => error?.code === 'INVALID_DAMAGE_TYPE'); });
test('direct KBは横25%・縦100%、blastはradial100%、Gearなしは0', () => { const direct = combat.knockbackPolicy({ hitKind: 'direct_hit', baseKnockback: 10, knockbackPowerBp: 2000 }); assert(Math.abs(direct.normalProjectileAdditional.horizontal - .5) < 1e-9); assert(Math.abs(direct.normalProjectileAdditional.vertical - 2) < 1e-9); assert.equal(direct.normalProjectileAdditional.radial, 0); const blast = combat.knockbackPolicy({ hitKind: 'blast_only', baseKnockback: 10, knockbackPowerBp: 2000 }); assert.equal(blast.normalProjectileAdditional.horizontal, 0); assert.equal(blast.normalProjectileAdditional.vertical, 0); assert(Math.abs(blast.normalProjectileAdditional.radial - 2) < 1e-9); assert.deepEqual(combat.knockbackPolicy({ hitKind: 'direct_hit', baseKnockback: 10 }).normalProjectileAdditional, { horizontal: 0, vertical: 0, radial: 0 }); });
test('conditional set valueはGearDomainを唯一の正本として投影する', () => { const values = { assault: combat.calculateBattleGearCombat({ battleGears: setLoadout('assault', 4), baseHp: 100, baseFuel: 10 }).conditional, life: combat.calculateBattleGearCombat({ battleGears: setLoadout('life', 4), baseHp: 100, baseFuel: 10 }).conditional, rescue: combat.calculateBattleGearCombat({ battleGears: setLoadout('rescue', 4), baseHp: 100, baseFuel: 10 }).conditional, last: combat.calculateBattleGearCombat({ battleGears: setLoadout('last_stand', 4), baseHp: 100, baseFuel: 10 }).conditional }; const from = (setId, threshold, effectId, field = 'valueBp') => domain.SETS.find((set) => set.id === setId).effects[threshold].conditionalEffects.find((entry) => entry.effectId === effectId)[field]; assert.equal(values.assault.directHitDamageBp, from('assault', 4, 'direct_hit_outgoing_damage')); assert.equal(values.life.lifeInitialShieldBp, from('life', 4, 'battle_start_max_hp_shield')); assert.equal(values.rescue.rescueNextAttackDamageBp, from('rescue', 4, 'ally_recovery_next_attack')); assert.equal(values.last.lastStandLowHpAttackBp, from('last_stand', 2, 'low_hp_attack')); assert.equal(values.last.lastStandLowHpNextAttackDamageBp, from('last_stand', 4, 'damage_taken_next_attack', 'lowHpValueBp')); });
test('8setは2/4のみ一度ずつ、6pieceとmixed 4+2でも多重発動しない', () => { domain.SET_IDS.forEach((setId) => { const four = combat.calculateBattleGearCombat({ battleGears: setLoadout(setId, 4), baseHp: 100, baseFuel: 10 }); const six = combat.calculateBattleGearCombat({ battleGears: setLoadout(setId, 6), baseHp: 100, baseFuel: 10 }); assert.deepEqual(six.activeSets, four.activeSets); }); const mixed = combat.calculateBattleGearCombat({ battleGears: [...setLoadout('assault', 4), ...setLoadout('life', 2)], baseHp: 100, baseFuel: 10 }); assert.equal(mixed.attackMultiplier, 1.08); assert.equal(mixed.maxHp, 110); });
test('soft caps、blast、None/Realistic/God sanityを固定する', () => { const capped = combat.calculateBattleGearCombat({ battleGears: Array.from({ length: 4 }, () => gear('engine', 'attack_pct', 0, 'life', [{ opId: 'crit_rate', valueBp: 2000 }, { opId: 'blast_power', valueBp: 2000 }])), baseHp: 100, baseFuel: 10 }); assert.equal(capped.critRateBp, 7500); assert.equal(capped.blastPowerBp, 6500); const blast = combat.calculateBattleGearCombat({ battleGears: [gear('auxiliary', 'blast_power', 2000)], baseHp: 100, baseFuel: 10 }); assert.equal(blast.blastDamageMultiplier, 1.2); assert.equal(blast.blastRangeMultiplier, 1.1); const none = combat.calculateBattleGearCombat({ battleGears: [], baseHp: 100, baseFuel: 50 }); const realistic = combat.calculateBattleGearCombat({ battleGears: [gear('barrel', 'flat_attack', 10, 'assault', [{ opId: 'attack_pct', valueBp: 600 }]), gear('armor', 'flat_hp', 10, 'life', [{ opId: 'hp_pct', valueBp: 600 }])], baseHp: 100, baseFuel: 50 }); const god = combat.calculateBattleGearCombat({ battleGears: [gear('barrel', 'flat_attack', 12, 'assault', [{ opId: 'attack_pct', valueBp: 3500 }]), gear('armor', 'flat_hp', 12, 'life', [{ opId: 'hp_pct', valueBp: 3500 }])], baseHp: 100, baseFuel: 50 }); assert(realistic.attackMultiplier > none.attackMultiplier && god.attackMultiplier > realistic.attackMultiplier); assert(realistic.maxHp > none.maxHp && god.maxHp > realistic.maxHp); });
console.log(`gear-combat: ${passed}/7 passed`);
