const assert = require('node:assert/strict');
const combat = require('../shared/gear-combat.js');
let passed = 0; const test = (name, fn) => { fn(); passed++; console.log(`  ok ${name}`); };
const c = { maxHp: 100, conditional: { rescue4: true, lastStand2: true, lastStand4: true, lifeInitialShieldBp: 800 }, shieldMultiplier: 1.2, receivedShieldMultiplier: 1.1 };

test('rescueは他者の実gainだけ対象へrefreshし、多重stackしない', () => { const targetCombat = { maxHp: 100, conditional: { rescue4: false, lastStand2: false, lastStand4: false } }; let result = combat.recordSupportEvent({ sourceCombat: c, targetState: combat.createRuntimeEffectsState(), sourceUnitId: 'A', targetUnitId: 'B', actualHealing: 1, actualShield: 0 }); assert.equal(result.grantedNextAttackDamageBp, 1000); result = combat.recordSupportEvent({ sourceCombat: c, targetState: result.state, sourceUnitId: 'A', targetUnitId: 'B', actualHealing: 1, actualShield: 1 }); assert.equal(result.grantedNextAttackDamageBp, 1000); assert.equal(combat.resolveRuntimeEffects({ combat: targetCombat, state: result.state, currentHp: 100 }).nextAttackDamageBp, 1000); for (const event of [{ sourceUnitId: 'A', targetUnitId: 'A', actualHealing: 1, actualShield: 0 }, { sourceUnitId: 'A', targetUnitId: 'B', actualHealing: 0, actualShield: 0 }]) assert.equal(combat.recordSupportEvent({ sourceCombat: c, targetState: combat.createRuntimeEffectsState(), ...event }).grantedNextAttackDamageBp, 0); });
test('last standは50%を常時再評価し、enemy attackだけnext actionへ付与する', () => { assert.equal(combat.resolveRuntimeEffects({ combat: c, currentHp: 51 }).lowHpAttackBp, 0); assert.equal(combat.resolveRuntimeEffects({ combat: c, currentHp: 50 }).lowHpAttackBp, 1000); assert.equal(combat.resolveRuntimeEffects({ combat: c, currentHp: 49 }).lowHpAttackBp, 1000); const low = combat.resolveRuntimeEffects({ combat: c, currentHp: 50, actualEnemyDamage: 1, damageType: 'normal_blast' }); assert.equal(low.nextAttackDamageBp, 1500); const high = combat.resolveRuntimeEffects({ combat: c, currentHp: 51, actualEnemyDamage: 1, damageType: 'direct_projectile' }); assert.equal(high.nextAttackDamageBp, 1000); for (const type of ['status', 'environmental', 'self', 'fixed']) assert.equal(combat.resolveRuntimeEffects({ combat: c, currentHp: 50, actualEnemyDamage: 1, damageType: type }).nextAttackDamageBp, 0); });
test('next-action buffはaction全体で維持し、completeで一回だけ消費する', () => { let state = combat.resolveRuntimeEffects({ combat: c, currentHp: 50, actualEnemyDamage: 1, damageType: 'direct_projectile' }).state; state = combat.recordSupportEvent({ sourceCombat: c, targetState: state, sourceUnitId: 'A', targetUnitId: 'B', actualHealing: 1 }).state; const action = combat.beginAttackAction(state); assert.equal(action.actionDamageBp, 2500); assert.equal(combat.beginAttackAction(action.state).actionDamageBp, 2500); const next = combat.completeAttackAction(action.state); assert.equal(combat.beginAttackAction(next).actionDamageBp, 0); });
test('life 4set shieldはsource/target倍率後に35% capを適用する', () => { const value = combat.initialShieldFromSets(c); assert.equal(value.requested, 10.56); assert.equal(value.gained, 10.56); assert.equal(combat.applyNumericShield({ baseShield: 100, maxHp: 100, sourceMultiplier: 2, targetMultiplier: 2 }).gained, 35); });
test('実damageはdamage type必須、runtime stateはexact schema', () => { assert.throws(() => combat.resolveRuntimeEffects({ combat: c, currentHp: 50, actualEnemyDamage: 1 }), (error) => error?.code === 'INVALID_DAMAGE_TYPE'); assert.throws(() => combat.beginAttackAction({ rescueNextAttackDamageBp: 0, lastStandNextAttackDamageBp: 0, extra: true }), (error) => error?.code === 'INVALID_RUNTIME_EFFECTS_STATE'); });
console.log(`gear-combat-runtime-effects: ${passed}/5 passed`);
