const assert = require('node:assert/strict');
const gear = require('../shared/gear-domain.js'); const gearStorage = require('../shared/gear-storage.js'); const presets = require('../shared/gear-presets.js'); const storageApi = require('../shared/gear-preset-storage.js'); const transactions = require('../shared/gear-transactions.js'); const foundation = require('../coop-mvp-foundation.js');
const ids = ['kyoryu']; const values = new Map(); const storage = { getItem: (key) => values.has(key) ? values.get(key) : null, setItem: (key, value) => values.set(key, String(value)), removeItem: (key) => values.delete(key) };
const lockManager = { async request(_name, _options, work) { return work({}); } };
function createQueuedLockManager() { const tails = new Map(); const active = new Map(); const peaks = new Map(); const names = []; return { request(name, _options, work) { names.push(name); const previous = tails.get(name) || Promise.resolve(); let release; const tail = new Promise((resolve) => { release = resolve; }); tails.set(name, tail); return previous.then(async () => { const nextActive = (active.get(name) || 0) + 1; active.set(name, nextActive); peaks.set(name, Math.max(peaks.get(name) || 0, nextActive)); try { return await work({}); } finally { active.set(name, nextActive - 1); release(); } }); }, peak: (name) => peaks.get(name) || 0, names: () => names.slice() }; }
function makeGear(gearId, slotId = 'barrel') { return gear.createGear({ gearId, generationSeed: `g:${gearId}`, enhancementSeed: `e:${gearId}`, sourceId: 'coop_boss', sourceDetail: { difficulty: 'normal' }, acquiredAt: '2026-08-26T00:00:00Z', qualityProfile: { id: 'p', starWeights: [{ id: 6, weight: 1 }], rarityWeights: [{ id: 'normal', weight: 1 }] }, setProfile: { id: 's', setWeights: [{ id: 'assault', weight: 1 }] }, slotId }); }
function stateWith(gearId) { const state = JSON.parse(JSON.stringify(presets.createInitialState(ids))); state.characters.kyoryu = { presets: ['preset1', 'preset2', 'preset3'].map((presetId, index) => ({ presetId, name: `Preset ${index + 1}`, slots: { barrel: index === 0 ? gearId : null, armor: null, core: null, engine: null, sight: null, auxiliary: null } })), modeDefaults: { cpu: 'preset1', free: 'preset1', online: 'preset1', coop: 'preset1' } }; return state; }
function install(gearItem) { gearStorage.saveGearState({ storageSchemaVersion: 3, inventory: gearItem ? [{ gear: gearItem, locked: false, favorite: false }] : [], tempBox: [], unclaimedRewards: [], rewardLedger: {}, resources: { powder: 0, blueprintShards: 0 } }, storage); }
function seedRaceStorage(gearItem, manager) { const raceValues = new Map(); const raceStorage = { getItem: (key) => raceValues.has(key) ? raceValues.get(key) : null, setItem: (key, value) => raceValues.set(key, String(value)), removeItem: (key) => raceValues.delete(key), gearMutationLockManager: manager }; gearStorage.saveGearState({ storageSchemaVersion: 3, inventory: [{ gear: gearItem, locked: false, favorite: false }], tempBox: [], unclaimedRewards: [], rewardLedger: {}, resources: { powder: 999, blueprintShards: 0 } }, raceStorage); const foundationState = foundation.createDefaultState(); foundationState.wallet.coins = 999; foundation.saveState(foundationState, raceStorage); storageApi.save(stateWith(gearItem.gearId), raceStorage, { characterIds: ids }); return raceStorage; }
async function main() {
  let passed = 0; const test = async (name, fn) => { await fn(); passed++; console.log(`  ok ${name}`); }; const reject = async (code, fn) => await assert.rejects(fn, (error) => error?.code === code);
  const item = makeGear('barrel-1'); install(item); storageApi.save(stateWith(item.gearId), storage, { characterIds: ids });
  await test('captureはinventoryから正slotのimmutable loadoutを返す', async () => { const captured = await storageApi.captureResolvedPresetForBattle({ characterId: 'kyoryu', mode: 'cpu' }, storage, { characterIds: ids, lockManager }); assert.equal(captured.slots.barrel.gearId, item.gearId); assert.equal(Object.isFrozen(captured.slots.barrel), true); install(null); assert.equal(captured.slots.barrel.gearId, item.gearId); });
  await test('capture後のpreset変更も既存captureへ影響しない', async () => { install(item); storageApi.save(stateWith(item.gearId), storage, { characterIds: ids }); const captured = await storageApi.captureResolvedPresetForBattle({ characterId: 'kyoryu', mode: 'cpu' }, storage, { characterIds: ids, lockManager }); await storageApi.mutateGearPresetsLocked((state) => presets.setPresetSlot(state, { characterId: 'kyoryu', presetId: 'preset1', slotId: 'barrel', gearId: null, characterIds: ids }), storage, { characterIds: ids, lockManager }); assert.equal(captured.slots.barrel.gearId, item.gearId); const after = await storageApi.captureResolvedPresetForBattle({ characterId: 'kyoryu', mode: 'cpu' }, storage, { characterIds: ids, lockManager }); assert.equal(after.slots.barrel, null); storageApi.save(stateWith(item.gearId), storage, { characterIds: ids }); });
  await test('stale/wrong slot/TEMP/unclaimedはfail closed', async () => { install(null); await reject('GEAR_PRESET_MISSING_GEAR', () => storageApi.captureResolvedPresetForBattle({ characterId: 'kyoryu', presetId: 'preset1' }, storage, { characterIds: ids, lockManager })); install(makeGear('barrel-1', 'armor')); await reject('GEAR_PRESET_SLOT_MISMATCH', () => storageApi.captureResolvedPresetForBattle({ characterId: 'kyoryu', presetId: 'preset1' }, storage, { characterIds: ids, lockManager })); const temp = makeGear('barrel-1'); gearStorage.saveGearState({ storageSchemaVersion: 3, inventory: [], tempBox: [{ gear: temp, locked: false, favorite: false, enteredAtMs: 1 }], unclaimedRewards: [], rewardLedger: {}, resources: { powder: 0, blueprintShards: 0 } }, storage); await reject('GEAR_PRESET_MISSING_GEAR', () => storageApi.captureResolvedPresetForBattle({ characterId: 'kyoryu', presetId: 'preset1' }, storage, { characterIds: ids, lockManager })); gearStorage.saveGearState({ storageSchemaVersion: 3, inventory: [], tempBox: [], unclaimedRewards: [{ rewardId: 'r1', sourceId: 'coop_boss', sourceDetail: { difficulty: 'normal' }, powder: 0, blueprintShards: 0, createdAtMs: 1, gears: [temp] }], rewardLedger: {}, resources: { powder: 0, blueprintShards: 0 } }, storage); await reject('GEAR_PRESET_MISSING_GEAR', () => storageApi.captureResolvedPresetForBattle({ characterId: 'kyoryu', presetId: 'preset1' }, storage, { characterIds: ids, lockManager })); });
  await test('WAL/no lockはcaptureとmutationをfail closed', async () => { values.set(storageApi.WAL_KEY, '{}'); await reject('PENDING_GEAR_TRANSACTION_EXISTS', () => storageApi.captureResolvedPresetForBattle({ characterId: 'kyoryu', presetId: 'preset1' }, storage, { characterIds: ids, lockManager })); values.delete(storageApi.WAL_KEY); await reject('STORAGE_LOCK_UNAVAILABLE', () => storageApi.mutateGearPresetsLocked((value) => value, storage, { characterIds: ids })); });
  await test('lock callbackを呼ばないmanagerはcaptureとmutationをfail closedする', async () => { install(item); storageApi.save(stateWith(item.gearId), storage, { characterIds: ids }); const beforePreset = values.get(storageApi.STORAGE_KEY); const beforeGear = values.get(gearStorage.GEAR_STORAGE_KEY); const noCallback = { request: () => Promise.resolve(undefined) }; await reject('STORAGE_LOCK_NOT_ACQUIRED', () => storageApi.captureResolvedPresetForBattle({ characterId: 'kyoryu', mode: 'cpu' }, storage, { characterIds: ids, lockManager: noCallback })); await reject('STORAGE_LOCK_NOT_ACQUIRED', () => storageApi.mutateGearPresetsLocked((state) => state, storage, { characterIds: ids, lockManager: noCallback })); assert.equal(values.get(storageApi.STORAGE_KEY), beforePreset); assert.equal(values.get(gearStorage.GEAR_STORAGE_KEY), beforeGear); });
  await test('captureはmode/presetIdのXORとexact inputを強制する', async () => { await reject('INVALID_CAPTURE_INPUT', () => storageApi.captureResolvedPresetForBattle({ characterId: 'kyoryu' }, storage, { characterIds: ids, lockManager })); await reject('INVALID_CAPTURE_INPUT', () => storageApi.captureResolvedPresetForBattle({ characterId: 'kyoryu', mode: 'cpu', presetId: 'preset1' }, storage, { characterIds: ids, lockManager })); await reject('INVALID_CAPTURE_INPUT', () => storageApi.captureResolvedPresetForBattle({ characterId: 'kyoryu', mode: 'cpu', extra: true }, storage, { characterIds: ids, lockManager })); });
  await test('Phase2B enhancementとcaptureは共通lockで直列化しold/new以外を返さない', async () => { const manager = createQueuedLockManager(); const beforeGear = makeGear('race-before'); const beforeStore = seedRaceStorage(beforeGear, manager); const [oldCapture] = await Promise.all([storageApi.captureResolvedPresetForBattle({ characterId: 'kyoryu', mode: 'cpu' }, beforeStore, { characterIds: ids, lockManager: manager }), transactions.enhanceStoredGearAtomic({ transactionId: 'race-before-tx', gearId: beforeGear.gearId, targetLevel: 1, createdAtMs: 1, storage: beforeStore, lockManager: manager })]); assert.equal(oldCapture.slots.barrel.enhancementLevel, 0); assert.equal((await storageApi.captureResolvedPresetForBattle({ characterId: 'kyoryu', mode: 'cpu' }, beforeStore, { characterIds: ids, lockManager: manager })).slots.barrel.enhancementLevel, 1); const afterGear = makeGear('race-after'); const afterStore = seedRaceStorage(afterGear, manager); const [, newCapture] = await Promise.all([transactions.enhanceStoredGearAtomic({ transactionId: 'race-after-tx', gearId: afterGear.gearId, targetLevel: 1, createdAtMs: 2, storage: afterStore, lockManager: manager }), storageApi.captureResolvedPresetForBattle({ characterId: 'kyoryu', mode: 'cpu' }, afterStore, { characterIds: ids, lockManager: manager })]); assert.equal(newCapture.slots.barrel.enhancementLevel, 1); assert.equal(manager.peak(storageApi.LOCK_NAME), 1); assert(manager.names().every((name) => name === storageApi.LOCK_NAME)); assert.equal(afterStore.getItem(storageApi.WAL_KEY), null); });
  await test('preset mutationとcaptureも共通lockで直列化する', async () => { const manager = createQueuedLockManager(); const gearItem = makeGear('preset-race'); const raceStorage = seedRaceStorage(gearItem, manager); const [, captured] = await Promise.all([storageApi.mutateGearPresetsLocked((state) => presets.setPresetSlot(state, { characterId: 'kyoryu', presetId: 'preset1', slotId: 'barrel', gearId: null, characterIds: ids }), raceStorage, { characterIds: ids, lockManager: manager }), storageApi.captureResolvedPresetForBattle({ characterId: 'kyoryu', mode: 'cpu' }, raceStorage, { characterIds: ids, lockManager: manager })]); assert.equal(captured.slots.barrel, null); assert.equal(manager.peak(storageApi.LOCK_NAME), 1); assert(manager.names().every((name) => name === storageApi.LOCK_NAME)); });
  console.log(`gear-preset-capture: ${passed}/8 passed`);
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
