const assert = require('node:assert/strict');
const snapshot = require('../shared/gear-battle-snapshot.js'); const gear = require('../shared/gear-domain.js');
let passed = 0; const test = (name, fn) => { fn(); passed++; console.log(`  ok ${name}`); }; const fail = (code, fn) => assert.throws(fn, (error) => error?.code === code);
function empty() { return { characterId: 'kyoryu', presetId: 'preset1', gearIds: [], slots: { barrel: null, armor: null, core: null, engine: null, sight: null, auxiliary: null } }; }
function makeGear(gearId, slotId = 'barrel', setId = 'assault') { return gear.createGear({ gearId, generationSeed: `g:${gearId}`, enhancementSeed: `e:${gearId}`, sourceId: 'coop_boss', sourceDetail: { difficulty: 'normal' }, acquiredAt: '2026-08-26T00:00:00Z', qualityProfile: { id: 'q', starWeights: [{ id: 6, weight: 1 }], rarityWeights: [{ id: 'mythic', weight: 1 }] }, setProfile: { id: 's', setWeights: [{ id: setId, weight: 1 }] }, slotId, setId }); }
function equipped(...items) { const value = empty(); items.forEach((item) => { value.slots[item.slotId] = item; value.gearIds.push(item.gearId); }); return value; }

test('empty snapshotはround trip、freeze、stable bytes、runtime初期値', () => { const value = snapshot.createBattleGearSnapshot({ resolvedLoadout: empty(), baseHp: 100, baseFuel: 50 }); assert.equal(Object.isFrozen(value), true); assert.equal(snapshot.stableSerialize(value), snapshot.stableSerialize(value)); assert.deepEqual(value.initialRuntimeState, { rescueNextAttackDamageBp: 0, lastStandNextAttackDamageBp: 0 }); assert.equal(JSON.stringify(value).includes('enhancementSeed'), false); });
test('exact/future/static derivedとruntime flag改ざんをreject', () => { const value = snapshot.createBattleGearSnapshot({ resolvedLoadout: empty(), baseHp: 100, baseFuel: 50 }); const unknown = structuredClone(value); unknown.extra = true; fail('INVALID_GEAR_BATTLE_SNAPSHOT', () => snapshot.validateBattleGearSnapshot(unknown, { baseHp: 100, baseFuel: 50 })); const future = structuredClone(value); future.version = 2; fail('UNSUPPORTED_FUTURE_GEAR_BATTLE_SNAPSHOT', () => snapshot.validateBattleGearSnapshot(future, { baseHp: 100, baseFuel: 50 })); const changed = structuredClone(value); changed.derivedStats.maxHp = 101; fail('TAMPERED_GEAR_BATTLE_SNAPSHOT', () => snapshot.validateBattleGearSnapshot(changed, { baseHp: 100, baseFuel: 50 })); const runtime = structuredClone(value); runtime.initialRuntimeState.rescueNextAttackDamageBp = 1000; fail('TAMPERED_GEAR_BATTLE_SNAPSHOT', () => snapshot.validateBattleGearSnapshot(runtime, { baseHp: 100, baseFuel: 50 })); });
test('battle viewはseedを漏らさずmain/sub roll整合とslot/duplicateをstrictに検証する', () => { const barrel = makeGear('barrel', 'barrel'); const value = snapshot.createBattleGearSnapshot({ resolvedLoadout: equipped(barrel), baseHp: 100, baseFuel: 50 }); assert.equal(JSON.stringify(value).includes('generationSeed'), false); const main = structuredClone(value); main.slots.barrel.mainOp.value += 1; fail('INVALID_BATTLE_GEAR', () => snapshot.validateBattleGearSnapshot(main, { baseHp: 100, baseFuel: 50 })); const sub = structuredClone(value); sub.slots.barrel.subs[0].valueBp += 1; fail('INVALID_BATTLE_GEAR', () => snapshot.validateBattleGearSnapshot(sub, { baseHp: 100, baseFuel: 50 })); const metadata = structuredClone(value); metadata.slots.barrel.subs[0].enhancementRollsBp.push(500); fail('INVALID_BATTLE_GEAR', () => snapshot.validateBattleGearSnapshot(metadata, { baseHp: 100, baseFuel: 50 })); const wrong = structuredClone(value); wrong.slots.barrel.slotId = 'armor'; fail('INVALID_BATTLE_GEAR', () => snapshot.validateBattleGearSnapshot(wrong, { baseHp: 100, baseFuel: 50 })); });
test('4set conditional capabilityはstatic snapshotとして再計算でき、発動値を焼き込まない', () => { const value = snapshot.createBattleGearSnapshot({ resolvedLoadout: equipped(makeGear('a', 'barrel'), makeGear('b', 'armor'), makeGear('c', 'core'), makeGear('d', 'engine')), baseHp: 100, baseFuel: 50 }); assert.equal(value.derivedStats.conditional.directHitDamageBp, 1200); assert.equal(value.derivedStats.damageReductionBp, 0); assert.equal(snapshot.validateBattleGearSnapshot(value, { baseHp: 100, baseFuel: 50 }).activeSets.length >= 2, true); });
test('resolved gearIdsとcanonical subsを照合し、relevant current stateでbytesが変わる', () => { const item = makeGear('same', 'barrel'); const bad = equipped(item); bad.gearIds = []; fail('INVALID_RESOLVED_LOADOUT', () => snapshot.createBattleGearSnapshot({ resolvedLoadout: bad, baseHp: 100, baseFuel: 50 })); const initial = snapshot.createBattleGearSnapshot({ resolvedLoadout: equipped(item), baseHp: 100, baseFuel: 50 }); const enhanced = gear.enhanceGear(item, 3); const changed = snapshot.createBattleGearSnapshot({ resolvedLoadout: equipped(enhanced), baseHp: 100, baseFuel: 50 }); assert.notEqual(snapshot.stableSerialize(initial), snapshot.stableSerialize(changed)); });
test('battle gearのstar/rarity/set/enhancement/duplicate/tuning改ざんをreject', () => { const barrel = makeGear('barrel-2'); const armor = makeGear('armor-2', 'armor'); const value = snapshot.createBattleGearSnapshot({ resolvedLoadout: equipped(barrel, armor), baseHp: 100, baseFuel: 50 }); for (const [path, changed] of [['star', 7], ['rarityId', 'unknown'], ['setId', 'unknown'], ['enhancementLevel', 13], ['balanceTuningVersion', 999]]) { const copy = structuredClone(value); copy.slots.barrel[path] = changed; fail('INVALID_BATTLE_GEAR', () => snapshot.validateBattleGearSnapshot(copy, { baseHp: 100, baseFuel: 50 })); } const duplicate = structuredClone(value); duplicate.slots.armor.gearId = duplicate.slots.barrel.gearId; fail('INVALID_BATTLE_GEAR', () => snapshot.validateBattleGearSnapshot(duplicate, { baseHp: 100, baseFuel: 50 })); });
test('presetIdはPhase 3Aのcanonical presetだけを受理する', () => { const value = snapshot.createBattleGearSnapshot({ resolvedLoadout: empty(), baseHp: 100, baseFuel: 50 }); const copy = structuredClone(value); copy.presetId = 'preset4'; fail('INVALID_GEAR_BATTLE_SNAPSHOT', () => snapshot.validateBattleGearSnapshot(copy, { baseHp: 100, baseFuel: 50 })); });
console.log(`gear-battle-snapshot: ${passed}/7 passed`);
