import { describe, expect, it } from 'vitest';

import { HttpError } from '../../server/security.js';
import { normalizeGitPath, validateIdentifier, validateSubmission } from '../../server/validation.js';
import { canonicalRecordBytes, serverTestConfig, submittedFile } from './server-fixtures.js';

function submission(file = submittedFile(
  'content/characters/sample-unit.json',
  'application/json',
  canonicalRecordBytes(),
)) {
  return {
    bundleId: 'a'.repeat(64),
    generatorVersion: '0.1.0',
    character: { id: 'sample-unit', slug: 'sample-unit', displayName: 'サンプルキャラクター' },
    files: [file],
    prBody: '## Content Studio\n\n- 自動確認: 成功\n',
  };
}

describe('server-side submission validation', () => {
  it('slugとcanonical JSONを再検証する', () => {
    const result = validateSubmission(submission(), serverTestConfig());
    expect(result.character.slug).toBe('sample-unit');
    expect(result.files[0].path).toBe('content/characters/sample-unit.json');
    expect(() => validateIdentifier('1-invalid')).toThrowError(HttpError);
    expect(() => validateIdentifier('sample--unit')).toThrowError(HttpError);

    const malformedRecord = JSON.parse(canonicalRecordBytes().toString('utf8'));
    malformedRecord.character.maxHp = 999_999;
    const malformedFile = submittedFile(
      'content/characters/sample-unit.json',
      'application/json',
      Buffer.from(JSON.stringify(malformedRecord), 'utf8'),
    );
    expect(() => validateSubmission(submission(malformedFile), serverTestConfig())).toThrowError(/正規キャラクターデータ/);
  });

  it('path traversalと許可外パスを拒否する', () => {
    expect(() => normalizeGitPath('../index.html')).toThrowError(HttpError);
    const file = submittedFile(
      'content/characters/other-unit.json',
      'application/json',
      Buffer.from(JSON.stringify({ id: 'sample-unit', slug: 'sample-unit' }), 'utf8'),
    );
    expect(() => validateSubmission(submission(file), serverTestConfig())).toThrowError(/許可されていない/);
  });

  it('申告容量、SHA-256、MIMEを信用しない', () => {
    const badLength = submission();
    badLength.files[0].byteLength += 1;
    expect(() => validateSubmission(badLength, serverTestConfig())).toThrowError(/実容量/);

    const badHash = submission();
    badHash.files[0].sha256 = '0'.repeat(64);
    expect(() => validateSubmission(badHash, serverTestConfig())).toThrowError(/ハッシュ/);

    const fakePng = submittedFile(
      'assets/content-studio/sample-unit/abcdef12/character.png',
      'image/png',
      Buffer.from('not-an-image'),
    );
    const withFakePng = submission();
    withFakePng.files.push(fakePng);
    expect(() => validateSubmission(withFakePng, serverTestConfig())).toThrowError(/magic bytes/);
  });

  it('任意JavaScriptのcatalogを拒否し固定JSONラッパーだけ許可する', () => {
    const unsafe = submittedFile(
      'generated/content-studio-catalog.js',
      'text/javascript',
      Buffer.from('globalThis.__CONTENT_STUDIO_CATALOG__ = {}; fetch("https://invalid");', 'utf8'),
    );
    const unsafeSubmission = submission();
    unsafeSubmission.files.push(unsafe);
    expect(() => validateSubmission(unsafeSubmission, serverTestConfig())).toThrowError(/固定ラッパー/);

    const safe = submittedFile(
      'generated/content-studio-catalog.js',
      'text/javascript',
      Buffer.from(
        '/* Generated by Content Studio. Do not edit manually. */\nglobalThis.__CONTENT_STUDIO_CATALOG__ = {"schemaVersion":1,"characters":{}};\n',
        'utf8',
      ),
    );
    const safeSubmission = submission();
    safeSubmission.files.push(safe);
    expect(validateSubmission(safeSubmission, serverTestConfig()).files).toHaveLength(2);
  });

  it('危険なHTML・制御文字・秘密らしきPR本文を拒否する', () => {
    const unsafeName = submission();
    unsafeName.character.displayName = '<img onerror=alert(1)>';
    expect(() => validateSubmission(unsafeName, serverTestConfig())).toThrowError(/危険/);

    const unsafePr = submission();
    unsafePr.prBody = `token: ${['ghp', 'abcdefghijklmnopqrstuvwxyz123456'].join('_')}`;
    expect(() => validateSubmission(unsafePr, serverTestConfig())).toThrowError(/秘密/);
  });
});
