import type { CharacterForm, DraftRecord, MotionParameters } from './types';
import { DRAFT_SCHEMA_VERSION } from './types';

export const DEFAULT_MOTION: MotionParameters = {
  frameCount: 8,
  fps: 8,
  durationMs: 1000,
  moveX: 0,
  moveY: 4,
  scaleAmount: 0.012,
  squashAmount: 0.01,
  rotationDegrees: 0.5,
  idlePause: 0.12,
  groundContact: 0.92,
  intensity: 1,
  flipHorizontal: false,
  canvasPadding: 18,
  outputSize: 512,
  lightweightPreview: false,
};

export const DEFAULT_CHARACTER: CharacterForm = {
  schemaVersion: 1,
  id: '',
  slug: '',
  displayName: '',
  attribute: 'neutral',
  classification: 'standard',
  rarity: 3,
  description: '',
  tags: [],
  maxHp: 100,
  attack: 3,
  defense: 3,
  speed: 3,
  weight: 3,
  movement: 'ground',
  blastMultiplier: 1,
  windMultiplier: 1,
  fuelMultiplier: 1,
  velocityMultiplier: 1,
  damageTakenMultiplier: 1,
  guideMultiplier: 1,
  gravityMultiplier: 1,
  specialVelocityMultiplier: 1,
  cpuTargetBias: 1,
  color: '#d9a441',
  sourceFacesLeft: false,
  spriteScale: 1,
  faceCrop: { x: 0.5, y: 0.3, width: 0.42 },
  matchupCrop: { x: 0.5, y: 0.32, width: 0.36 },
  normalSkillId: 'standard-projectile',
  specialEnabled: false,
  specialName: '未設定',
  specialDescription: '必殺技は未設定です。',
  specialTemplate: 'single',
  specialParameters: {
    power: 1.35,
    projectileCount: 1,
    intervalMs: 0,
    projectileSpeed: 1,
    gravityMultiplier: 1,
    explosionRadius: 1.25,
    penetrationCount: 0,
    cooldownTurns: 4,
    knockback: 0,
    statusChance: 0,
    statusDurationTurns: 0,
    healing: 0,
    effectRef: 'default-impact',
    soundRef: 'default-special',
  },
  customImplementationNote: '',
  implementationVersion: '1',
  unlock: {
    enabled: false,
    type: 'always',
    target: 0,
    achievementId: '',
    description: '',
  },
};

export function createDraft(id: string = crypto.randomUUID()): DraftRecord {
  const now = new Date().toISOString();
  return {
    schemaVersion: DRAFT_SCHEMA_VERSION,
    id,
    title: '新しいキャラクター',
    createdAt: now,
    updatedAt: now,
    lastStep: 'image',
    character: structuredClone(DEFAULT_CHARACTER),
    imageInfo: null,
    hitImageInfo: null,
    editor: {
      tolerance: 32,
      edgeFeather: 1,
      brushSize: 28,
      offsetX: 0,
      offsetY: 0,
      scale: 0.86,
      flipHorizontal: false,
      padding: 24,
      outputSize: 512,
      zoom: 1,
      tool: 'pan',
    },
    motionPreset: 'standard',
    motionAction: 'idle',
    actionPreset: 'idle-standard',
    motion: structuredClone(DEFAULT_MOTION),
    partDetection: {
      status: 'idle',
      parts: [],
      focusPartId: null,
      anchorPartId: null,
      analyzedAt: null,
    },
    landmarks: {
      status: 'idle',
      facing: 'right',
      ground: { x: 0.5, y: 0.9 },
      muzzle: { x: 0.8, y: 0.5 },
      detectedAt: null,
    },
    motionIntensity: {
      'move-forward': 'standard',
      'move-backward': 'standard',
      fire: 'standard',
      hit: 'standard',
      land: 'standard',
    },
    generatedClips: [],
    publishMode: 'pr-only',
    preview: {
      background: 'game',
      direction: 'right',
      size: 'normal',
      showAnchor: true,
      showCollision: true,
      playing: true,
    },
    validation: [],
    processingOperations: [],
    historyStatus: 'clean',
    mockScenario: 'success',
    sourceIdentity: null,
    legacyTargetId: null,
  };
}
