(function initKatamonGearCombat(root, factory) {
  const api = factory(root);
  if (typeof module === 'object' && module.exports) module.exports = api;
  if (root) root.KatamonGearCombat = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function createKatamonGearCombat(root) {
  'use strict';
  const BP = 10000; const BASE_ATTACK = 100; const BASE_DEFENSE = 100; const BASE_CRIT_DAMAGE_BP = 15000; const SHIELD_CAP_BP = 3500;
  class GearCombatError extends Error { constructor(code, message) { super(message || code); this.name = 'GearCombatError'; this.code = code; } }
  const fail = (code, message) => { throw new GearCombatError(code, message); };
  const clone = (value) => JSON.parse(JSON.stringify(value));
  const freeze = (value) => { if (value && typeof value === 'object' && !Object.isFrozen(value)) { Object.freeze(value); Object.values(value).forEach(freeze); } return value; };
  const nonNegative = (value, name) => { if (!Number.isFinite(value) || value < 0) fail('INVALID_COMBAT_INPUT', `${name} must be finite and non-negative`); return value; };
  const integer = (value, name) => { if (!Number.isSafeInteger(value) || value < 0) fail('INVALID_COMBAT_INPUT', `${name} must be a non-negative safe integer`); return value; };
  function domain() { if (typeof module === 'object' && module.exports && typeof require === 'function') return require('./gear-domain.js'); if (root?.KatamonGearDomain) return root.KatamonGearDomain; fail('GEAR_DOMAIN_UNAVAILABLE'); }
  const multiplier = (bp) => 1 + (bp / BP); const setThreshold = (aggregate, setId, threshold) => aggregate.activeSetEffects.some((entry) => entry.setId === setId && entry.threshold === threshold); const effect = (aggregate, id) => aggregate.conditionalEffects.find((entry) => entry.effectId === id) || null; const effectValue = (aggregate, id, field = 'valueBp') => effect(aggregate, id)?.[field] || 0;
  function calculateFromAggregate(aggregate, { baseHp, baseFuel }) {
    nonNegative(baseHp, 'baseHp'); nonNegative(baseFuel, 'baseFuel'); const stats = aggregate.stats; const attack = (BASE_ATTACK + stats.flatAttack) * multiplier(stats.attackPctBp); const defense = (BASE_DEFENSE + stats.flatDefense) * multiplier(stats.defensePctBp); const maxHp = Math.round((baseHp + stats.flatHp) * multiplier(stats.hpPctBp)); const maxFuel = Math.round(baseFuel * multiplier(stats.maxFuelBp)); const d = domain(); const critRate = d.applySoftCap('crit_rate', stats.critRateBp); const critDamage = d.applySoftCap('crit_damage', BASE_CRIT_DAMAGE_BP + stats.critDamageBp); const statusResistance = d.applySoftCap('status_resistance', stats.statusResistanceBp); const blastPower = d.applySoftCap('blast_power', stats.blastPowerBp); const healPower = d.applySoftCap('heal_power', stats.healPowerBp); const receivedHeal = d.applySoftCap('received_heal', stats.receivedHealBp); const shieldPower = d.applySoftCap('shield_power', stats.shieldPowerBp); const receivedShield = d.applySoftCap('received_shield', stats.receivedShieldBp);
    const conditional = { directHitDamageBp: effectValue(aggregate, 'direct_hit_outgoing_damage'), directHitTakenReductionBp: effectValue(aggregate, 'direct_hit_damage_taken_reduction'), blastRangeBp: stats.blastRangeBp, lifeInitialShieldBp: effectValue(aggregate, 'battle_start_max_hp_shield'), rescueNextAttackDamageBp: effectValue(aggregate, 'ally_recovery_next_attack'), lastStandLowHpAttackBp: effectValue(aggregate, 'low_hp_attack'), lastStandNextAttackDamageBp: effectValue(aggregate, 'damage_taken_next_attack'), lastStandLowHpNextAttackDamageBp: effectValue(aggregate, 'damage_taken_next_attack', 'lowHpValueBp'), lastStandHpThresholdBp: effectValue(aggregate, 'damage_taken_next_attack', 'hpThresholdBp'), rescue4: setThreshold(aggregate, 'rescue', 4), lastStand2: setThreshold(aggregate, 'last_stand', 2), lastStand4: setThreshold(aggregate, 'last_stand', 4) };
    return freeze({ version: 1, baseHp, baseFuel, flatAttack: stats.flatAttack, staticAttackPctBp: stats.attackPctBp, effectiveAttack: attack, attackMultiplier: attack / BASE_ATTACK, effectiveDefense: defense, defenseMultiplier: BASE_DEFENSE / (BASE_DEFENSE + ((defense - BASE_DEFENSE) * .5)), maxHp, maxFuel, currentFuelAtBattleStart: maxFuel, critRateBp: critRate.effectiveBp, critDamageBp: critDamage.effectiveBp, critDamageMultiplier: critDamage.effectiveBp / BP, blastPowerBp: blastPower.effectiveBp, blastDamageMultiplier: multiplier(blastPower.effectiveBp), blastRangeMultiplier: 1 + ((blastPower.effectiveBp / BP) * .5) + (stats.blastRangeBp / BP), knockbackPowerBp: stats.knockbackPowerBp, knockbackResistanceBp: stats.knockbackResistanceBp, statusResistanceBp: statusResistance.effectiveBp, healingMultiplier: multiplier(healPower.effectiveBp), receivedHealingMultiplier: multiplier(receivedHeal.effectiveBp), shieldMultiplier: multiplier(shieldPower.effectiveBp), receivedShieldMultiplier: multiplier(receivedShield.effectiveBp), damageReductionBp: 0, activeSets: clone(aggregate.activeSetEffects), setCounts: clone(aggregate.setCounts), conditional });
  }
  function calculateGearCombat({ loadout = [], baseHp, baseFuel }) { return calculateFromAggregate(domain().aggregateLoadout(loadout), { baseHp, baseFuel }); }
  function calculateBattleGearCombat({ battleGears = [], baseHp, baseFuel }) { const d = domain(); if (!Array.isArray(battleGears) || battleGears.length > d.SLOT_IDS.length) fail('INVALID_BATTLE_GEARS'); const stats = { flatAttack: 0, flatHp: 0, flatDefense: 0, attackPctBp: 0, hpPctBp: 0, defensePctBp: 0, maxFuelBp: 0, critRateBp: 0, critDamageBp: 0, blastPowerBp: 0, blastRangeBp: 0, knockbackPowerBp: 0, knockbackResistanceBp: 0, statusResistanceBp: 0, healPowerBp: 0, receivedHealBp: 0, shieldPowerBp: 0, receivedShieldBp: 0, outgoingDamageConditionalBp: 0, incomingDamageConditionalBp: 0 }; const setCounts = Object.fromEntries(d.SET_IDS.map((id) => [id, 0])); const activeSetEffects = []; const conditionalEffects = []; const bucket = Object.fromEntries(d.SUB_OPS.map((entry) => [entry.id, entry.bucket])); bucket.max_fuel = 'maxFuelBp'; battleGears.filter(Boolean).forEach((item) => { const fixed = item.slotId === 'barrel' ? 'flatAttack' : item.slotId === 'armor' ? 'flatHp' : item.slotId === 'core' ? 'flatDefense' : null; stats[fixed || bucket[item.mainOp.opId]] += item.mainOp.value; item.subs.forEach((sub) => { stats[bucket[sub.opId]] += sub.valueBp; }); setCounts[item.setId] += 1; }); d.SETS.forEach((set) => [2, 4].forEach((threshold) => { if (setCounts[set.id] < threshold) return; const entry = set.effects[threshold]; Object.entries(entry.stats).forEach(([key, value]) => { stats[key] += value; }); const conditions = entry.conditionalEffects.map((value) => ({ setId: set.id, threshold, ...clone(value) })); conditionalEffects.push(...conditions); activeSetEffects.push({ setId: set.id, threshold, stats: clone(entry.stats), conditionalEffects: conditions }); })); return calculateFromAggregate({ stats, setCounts, activeSetEffects, conditionalEffects }, { baseHp, baseFuel }); }
  const DAMAGE_TYPES = freeze(['direct_projectile', 'normal_blast', 'status', 'environmental', 'fixed', 'self']);
  function assertDamageType(type) { if (!DAMAGE_TYPES.includes(type)) fail('INVALID_DAMAGE_TYPE'); return type; }
  function isCritEligibleDamageType(type) { assertDamageType(type); return type === 'direct_projectile' || type === 'normal_blast'; }
  function conditionalDamageModifiers({ combat, damageType }) { assertDamageType(damageType); return freeze({ outgoingDamageBp: damageType === 'direct_projectile' ? combat.conditional.directHitDamageBp : 0, incomingDamageReductionBp: damageType === 'direct_projectile' ? combat.conditional.directHitTakenReductionBp : 0 }); }
  function resolveAttackMultiplier({ combat, runtimeAttackPctBp = 0 }) { integer(runtimeAttackPctBp, 'runtimeAttackPctBp'); if (![0, combat.conditional.lastStandLowHpAttackBp].includes(runtimeAttackPctBp)) fail('INVALID_RUNTIME_ATTACK_PCT'); return ((BASE_ATTACK + combat.flatAttack) * multiplier(combat.staticAttackPctBp + runtimeAttackPctBp)) / BASE_ATTACK; }
  function calculateDamagePipeline({ baseDamage, attackMultiplier = 1, modifierBp = 0, isCrit = false, critDamageMultiplier = 1.5, defenseMultiplier = 1, damageReductionBp = 0, numericShield = 0, hp = 0 }) { nonNegative(baseDamage, 'baseDamage'); nonNegative(attackMultiplier, 'attackMultiplier'); integer(modifierBp, 'modifierBp'); nonNegative(critDamageMultiplier, 'critDamageMultiplier'); nonNegative(defenseMultiplier, 'defenseMultiplier'); integer(damageReductionBp, 'damageReductionBp'); nonNegative(numericShield, 'numericShield'); nonNegative(hp, 'hp'); const afterAttack = baseDamage * attackMultiplier; const afterModifiers = afterAttack * multiplier(modifierBp); const afterCrit = afterModifiers * (isCrit ? critDamageMultiplier : 1); const afterDefense = afterCrit * defenseMultiplier; const afterReduction = afterDefense * (1 - Math.min(4000, damageReductionBp) / BP); const shieldDamage = Math.min(numericShield, afterReduction); const hpDamage = afterReduction - shieldDamage; return freeze({ afterAttack, afterModifiers, afterCrit, afterDefense, afterReduction, shieldDamage, hpDamage, shieldAfter: numericShield - shieldDamage, hpAfter: Math.max(0, hp - hpDamage) }); }
  function statusSuccessChance(baseStatusChanceBp, statusResistanceBp) { integer(baseStatusChanceBp, 'baseStatusChanceBp'); integer(statusResistanceBp, 'statusResistanceBp'); return Math.max(0, Math.round(baseStatusChanceBp * (1 - Math.min(BP, statusResistanceBp) / BP))); }
  function finalHealing(baseHealing, sourceMultiplier = 1, targetMultiplier = 1) { return nonNegative(baseHealing, 'baseHealing') * nonNegative(sourceMultiplier, 'sourceMultiplier') * nonNegative(targetMultiplier, 'targetMultiplier'); }
  const finalShieldGain = finalHealing;
  function applyNumericShield({ currentShield = 0, baseShield, maxHp, sourceMultiplier = 1, targetMultiplier = 1 }) { const cap = nonNegative(maxHp, 'maxHp') * (SHIELD_CAP_BP / BP); const requested = finalShieldGain(baseShield, sourceMultiplier, targetMultiplier); const gained = Math.max(0, Math.min(requested, cap - nonNegative(currentShield, 'currentShield'))); return freeze({ cap, requested, gained, shieldAfter: currentShield + gained }); }
  function initialShieldFromSets(combat) { return applyNumericShield({ baseShield: combat.maxHp * (combat.conditional.lifeInitialShieldBp / BP), maxHp: combat.maxHp, sourceMultiplier: combat.shieldMultiplier, targetMultiplier: combat.receivedShieldMultiplier }); }
  function knockbackPolicy({ hitKind, baseKnockback = 0, knockbackPowerBp = 0, knockbackResistanceBp = 0 }) { nonNegative(baseKnockback, 'baseKnockback'); integer(knockbackPowerBp, 'knockbackPowerBp'); integer(knockbackResistanceBp, 'knockbackResistanceBp'); const resistanceMultiplier = 1 / (1 + (knockbackResistanceBp / BP)); const powerMultiplier = multiplier(knockbackPowerBp); const gearAdditional = baseKnockback * (powerMultiplier - 1) * resistanceMultiplier; const empty = { horizontal: 0, vertical: 0, radial: 0 }; if (hitKind === 'direct_hit') return freeze({ mode: 'direct_popup', resistanceMultiplier, finalKnockback: baseKnockback * powerMultiplier * resistanceMultiplier, normalProjectileAdditional: { horizontal: gearAdditional * .25, vertical: gearAdditional, radial: 0 } }); if (hitKind === 'blast_only') return freeze({ mode: 'radial', resistanceMultiplier, finalKnockback: baseKnockback * powerMultiplier * resistanceMultiplier, normalProjectileAdditional: { horizontal: 0, vertical: 0, radial: gearAdditional } }); if (hitKind === 'existing_knockback') return freeze({ mode: 'existing_knockback', resistanceMultiplier, finalKnockback: baseKnockback * powerMultiplier * resistanceMultiplier, normalProjectileAdditional: empty }); fail('INVALID_KNOCKBACK_HIT_KIND'); }
  function createRuntimeEffectsState() { return freeze({ rescueNextAttackDamageBp: 0, lastStandNextAttackDamageBp: 0 }); }
  function runtimeState(combat, state) { const value = state || createRuntimeEffectsState(); if (!value || typeof value !== 'object' || Array.isArray(value) || Object.keys(value).sort().join(',') !== 'lastStandNextAttackDamageBp,rescueNextAttackDamageBp') fail('INVALID_RUNTIME_EFFECTS_STATE'); const d = domain(); const find = (setId, threshold, effectId, field = 'valueBp') => d.SETS.find((set) => set.id === setId).effects[threshold].conditionalEffects.find((entry) => entry.effectId === effectId)[field]; const rescue = find('rescue', 4, 'ally_recovery_next_attack'); const last = find('last_stand', 4, 'damage_taken_next_attack'); const lastLow = find('last_stand', 4, 'damage_taken_next_attack', 'lowHpValueBp'); if (![0, rescue].includes(value.rescueNextAttackDamageBp) || ![0, last, lastLow].includes(value.lastStandNextAttackDamageBp) || (!combat?.conditional?.lastStand4 && value.lastStandNextAttackDamageBp !== 0)) fail('INVALID_RUNTIME_EFFECTS_STATE'); return clone(value); }
  function resolveRuntimeEffects({ combat, state = createRuntimeEffectsState(), currentHp, actualEnemyDamage = 0, damageType = null }) { nonNegative(currentHp, 'currentHp'); nonNegative(actualEnemyDamage, 'actualEnemyDamage'); const next = runtimeState(combat, state); const threshold = combat.conditional.lastStandHpThresholdBp || 5000; const lowHp = currentHp / combat.maxHp <= threshold / BP; const runtimeAttackPctBp = combat.conditional.lastStand2 && lowHp ? combat.conditional.lastStandLowHpAttackBp : 0; if (actualEnemyDamage > 0 && damageType === null) fail('INVALID_DAMAGE_TYPE'); if (actualEnemyDamage > 0) assertDamageType(damageType); if (combat.conditional.lastStand4 && actualEnemyDamage > 0 && ['direct_projectile', 'normal_blast'].includes(damageType)) next.lastStandNextAttackDamageBp = lowHp ? combat.conditional.lastStandLowHpNextAttackDamageBp : combat.conditional.lastStandNextAttackDamageBp; return freeze({ state: freeze(next), runtimeAttackPctBp, attackMultiplier: resolveAttackMultiplier({ combat, runtimeAttackPctBp }), nextAttackDamageBp: next.rescueNextAttackDamageBp + next.lastStandNextAttackDamageBp }); }
  function recordSupportEvent({ sourceCombat, targetCombat, targetState = createRuntimeEffectsState(), sourceUnitId, targetUnitId, actualHealing = 0, actualShield = 0 }) { if (!sourceCombat?.conditional || !targetCombat?.conditional || typeof sourceUnitId !== 'string' || !sourceUnitId || typeof targetUnitId !== 'string' || !targetUnitId) fail('INVALID_RECOVERY_EVENT'); nonNegative(actualHealing, 'actualHealing'); nonNegative(actualShield, 'actualShield'); const next = runtimeState(targetCombat, targetState); const didGrant = sourceCombat.conditional.rescue4 && sourceUnitId !== targetUnitId && (actualHealing > 0 || actualShield > 0); if (didGrant) next.rescueNextAttackDamageBp = sourceCombat.conditional.rescueNextAttackDamageBp; return freeze({ state: freeze(next), didGrant, grantedNextAttackDamageBp: didGrant ? sourceCombat.conditional.rescueNextAttackDamageBp : 0 }); }
  function beginAttackAction({ combat, state }) { const checked = runtimeState(combat, state); return freeze({ actionDamageBp: checked.rescueNextAttackDamageBp + checked.lastStandNextAttackDamageBp, state: freeze(checked) }); }
  function completeAttackAction({ combat, state }) { runtimeState(combat, state); return createRuntimeEffectsState(); }
  function consumeAttackRuntimeEffects({ combat, state }) { const action = beginAttackAction({ combat, state }); return freeze({ appliedDamageBp: action.actionDamageBp, nextState: completeAttackAction({ combat, state: action.state }) }); }
  return freeze({ GEAR_COMBAT_VERSION: 1, BASE_ATTACK, BASE_DEFENSE, BASE_CRIT_DAMAGE_BP, SHIELD_CAP_BP, DAMAGE_TYPES, calculateGearCombat, calculateBattleGearCombat, resolveAttackMultiplier, calculateDamagePipeline, isCritEligibleDamageType, conditionalDamageModifiers, statusSuccessChance, finalHealing, finalShieldGain, applyNumericShield, initialShieldFromSets, knockbackPolicy, createRuntimeEffectsState, resolveRuntimeEffects, recordSupportEvent, beginAttackAction, completeAttackAction, consumeAttackRuntimeEffects });
});
