(function initKatamonGearCombat(root, factory) {
  const api = factory(root);
  if (typeof module === 'object' && module.exports) module.exports = api;
  if (root) root.KatamonGearCombat = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function createKatamonGearCombat(root) {
  'use strict';
  const BP = 10000; const BASE_ATTACK = 100; const BASE_DEFENSE = 100; const BASE_CRIT_DAMAGE_BP = 15000; const SHIELD_CAP_BP = 3500;
  class GearCombatError extends Error { constructor(code, message) { super(message || code); this.name = 'GearCombatError'; this.code = code; } }
  const fail = (code, message) => { throw new GearCombatError(code, message); };
  const clone = (value) => JSON.parse(JSON.stringify(value));
  const freeze = (value) => { if (value && typeof value === 'object' && !Object.isFrozen(value)) { Object.freeze(value); Object.values(value).forEach(freeze); } return value; };
  const nonNegative = (value, name) => { if (!Number.isFinite(value) || value < 0) fail('INVALID_COMBAT_INPUT', `${name} must be finite and non-negative`); return value; };
  const integer = (value, name) => { if (!Number.isSafeInteger(value) || value < 0) fail('INVALID_COMBAT_INPUT', `${name} must be a non-negative safe integer`); return value; };
  function domain() { if (typeof module === 'object' && module.exports && typeof require === 'function') return require('./gear-domain.js'); if (root?.KatamonGearDomain) return root.KatamonGearDomain; fail('GEAR_DOMAIN_UNAVAILABLE', 'gear domain is unavailable'); }
  const multiplier = (bp) => 1 + (bp / BP);
  const setThreshold = (aggregate, setId, threshold) => aggregate.activeSetEffects.some((entry) => entry.setId === setId && entry.threshold === threshold);
  function calculateFromAggregate(aggregate, { baseHp, baseFuel }) {
    nonNegative(baseHp, 'baseHp'); nonNegative(baseFuel, 'baseFuel'); const stats = aggregate.stats;
    const attack = (BASE_ATTACK + stats.flatAttack) * multiplier(stats.attackPctBp);
    const defense = (BASE_DEFENSE + stats.flatDefense) * multiplier(stats.defensePctBp);
    const maxHp = Math.round((baseHp + stats.flatHp) * multiplier(stats.hpPctBp));
    const maxFuel = Math.round(baseFuel * multiplier(stats.maxFuelBp));
    const critRate = domain().applySoftCap('crit_rate', stats.critRateBp); const critDamage = domain().applySoftCap('crit_damage', BASE_CRIT_DAMAGE_BP + stats.critDamageBp);
    const statusResistance = domain().applySoftCap('status_resistance', stats.statusResistanceBp); const blastPower = domain().applySoftCap('blast_power', stats.blastPowerBp);
    const healPower = domain().applySoftCap('heal_power', stats.healPowerBp); const receivedHeal = domain().applySoftCap('received_heal', stats.receivedHealBp);
    const shieldPower = domain().applySoftCap('shield_power', stats.shieldPowerBp); const receivedShield = domain().applySoftCap('received_shield', stats.receivedShieldBp);
    // Conditional effects are capabilities, never currently-active bonuses.
    // Runtime state decides whether/when they apply after battle start.
    const damageReductionBp = 0;
    const conditional = { directHitDamageBp: setThreshold(aggregate, 'assault', 4) ? 1200 : 0, directHitTakenReductionBp: setThreshold(aggregate, 'fortify', 4) ? 1200 : 0, blastRangeBp: stats.blastRangeBp, lifeInitialShieldBp: setThreshold(aggregate, 'life', 4) ? 800 : 0, rescue4: setThreshold(aggregate, 'rescue', 4), lastStand2: setThreshold(aggregate, 'last_stand', 2), lastStand4: setThreshold(aggregate, 'last_stand', 4) };
    return freeze({ version: 1, baseHp, baseFuel, effectiveAttack: attack, attackMultiplier: attack / BASE_ATTACK, effectiveDefense: defense, defenseMultiplier: BASE_DEFENSE / (BASE_DEFENSE + ((defense - BASE_DEFENSE) * 0.5)), maxHp, maxFuel, currentFuelAtBattleStart: maxFuel, critRateBp: critRate.effectiveBp, critDamageBp: critDamage.effectiveBp, critDamageMultiplier: critDamage.effectiveBp / BP, blastPowerBp: blastPower.effectiveBp, blastDamageMultiplier: multiplier(blastPower.effectiveBp), blastRangeMultiplier: 1 + ((blastPower.effectiveBp / BP) * 0.5) + (stats.blastRangeBp / BP), knockbackPowerBp: stats.knockbackPowerBp, knockbackResistanceBp: stats.knockbackResistanceBp, statusResistanceBp: statusResistance.effectiveBp, healingMultiplier: multiplier(healPower.effectiveBp), receivedHealingMultiplier: multiplier(receivedHeal.effectiveBp), shieldMultiplier: multiplier(shieldPower.effectiveBp), receivedShieldMultiplier: multiplier(receivedShield.effectiveBp), damageReductionBp, activeSets: clone(aggregate.activeSetEffects), setCounts: clone(aggregate.setCounts), conditional });
  }
  function calculateGearCombat({ loadout = [], baseHp, baseFuel }) { return calculateFromAggregate(domain().aggregateLoadout(loadout), { baseHp, baseFuel }); }
  function calculateBattleGearCombat({ battleGears = [], baseHp, baseFuel }) { const d = domain(); if (!Array.isArray(battleGears) || battleGears.length > d.SLOT_IDS.length) fail('INVALID_BATTLE_GEARS'); const stats = { flatAttack: 0, flatHp: 0, flatDefense: 0, attackPctBp: 0, hpPctBp: 0, defensePctBp: 0, maxFuelBp: 0, critRateBp: 0, critDamageBp: 0, blastPowerBp: 0, blastRangeBp: 0, knockbackPowerBp: 0, knockbackResistanceBp: 0, statusResistanceBp: 0, healPowerBp: 0, receivedHealBp: 0, shieldPowerBp: 0, receivedShieldBp: 0, outgoingDamageConditionalBp: 0, incomingDamageConditionalBp: 0 }; const setCounts = Object.fromEntries(d.SET_IDS.map((id) => [id, 0])); const activeSetEffects = []; const bucketByOp = Object.fromEntries(d.SUB_OPS.map((entry) => [entry.id, entry.bucket])); bucketByOp.max_fuel = 'maxFuelBp'; battleGears.filter(Boolean).forEach((gear) => { const fixed = gear.slotId === 'barrel' ? 'flatAttack' : gear.slotId === 'armor' ? 'flatHp' : gear.slotId === 'core' ? 'flatDefense' : null; stats[fixed || bucketByOp[gear.mainOp.opId]] += gear.mainOp.value; gear.subs.forEach((sub) => { stats[bucketByOp[sub.opId]] += sub.valueBp; }); setCounts[gear.setId] += 1; }); d.SETS.forEach((set) => { [2, 4].forEach((threshold) => { if (setCounts[set.id] < threshold) return; const effect = set.effects[threshold]; Object.entries(effect.stats).forEach(([key, value]) => { stats[key] += value; }); const conditionalEffects = effect.conditionalEffects.map((entry) => ({ setId: set.id, threshold, ...clone(entry) })); activeSetEffects.push({ setId: set.id, threshold, stats: clone(effect.stats), conditionalEffects }); }); }); return calculateFromAggregate({ stats, setCounts, activeSetEffects }, { baseHp, baseFuel }); }
  const DAMAGE_TYPES = freeze(['direct_projectile', 'normal_blast', 'status', 'environmental', 'fixed', 'self']);
  function assertDamageType(type) { if (!DAMAGE_TYPES.includes(type)) fail('INVALID_DAMAGE_TYPE', 'damage type is invalid'); return type; }
  function isCritEligibleDamageType(type) { return type === 'direct_projectile' || type === 'normal_blast'; }
  function conditionalDamageModifiers({ combat, damageType }) { assertDamageType(damageType); return freeze({ outgoingDamageBp: damageType === 'direct_projectile' ? combat.conditional.directHitDamageBp : 0, incomingDamageReductionBp: damageType === 'direct_projectile' ? combat.conditional.directHitTakenReductionBp : 0 }); }
  function calculateDamagePipeline({ baseDamage, attackMultiplier = 1, modifierBp = 0, isCrit = false, critDamageMultiplier = 1.5, defenseMultiplier = 1, damageReductionBp = 0, numericShield = 0, hp = 0 }) { nonNegative(baseDamage, 'baseDamage'); nonNegative(attackMultiplier, 'attackMultiplier'); integer(modifierBp, 'modifierBp'); nonNegative(critDamageMultiplier, 'critDamageMultiplier'); nonNegative(defenseMultiplier, 'defenseMultiplier'); integer(damageReductionBp, 'damageReductionBp'); nonNegative(numericShield, 'numericShield'); nonNegative(hp, 'hp'); const afterAttack = baseDamage * attackMultiplier; const afterModifiers = afterAttack * multiplier(modifierBp); const afterCrit = afterModifiers * (isCrit ? critDamageMultiplier : 1); const afterDefense = afterCrit * defenseMultiplier; const afterReduction = afterDefense * (1 - Math.min(4000, damageReductionBp) / BP); const shieldDamage = Math.min(numericShield, afterReduction); const hpDamage = afterReduction - shieldDamage; return freeze({ afterAttack, afterModifiers, afterCrit, afterDefense, afterReduction, shieldDamage, hpDamage, shieldAfter: numericShield - shieldDamage, hpAfter: Math.max(0, hp - hpDamage) }); }
  function statusSuccessChance(baseStatusChanceBp, statusResistanceBp) { integer(baseStatusChanceBp, 'baseStatusChanceBp'); integer(statusResistanceBp, 'statusResistanceBp'); return Math.max(0, Math.round(baseStatusChanceBp * (1 - Math.min(BP, statusResistanceBp) / BP))); }
  function finalHealing(baseHealing, sourceMultiplier = 1, targetMultiplier = 1) { return nonNegative(baseHealing, 'baseHealing') * nonNegative(sourceMultiplier, 'sourceMultiplier') * nonNegative(targetMultiplier, 'targetMultiplier'); }
  const finalShieldGain = finalHealing;
  function applyNumericShield({ currentShield = 0, baseShield, maxHp, sourceMultiplier = 1, targetMultiplier = 1 }) { const cap = nonNegative(maxHp, 'maxHp') * (SHIELD_CAP_BP / BP); const requested = finalShieldGain(baseShield, sourceMultiplier, targetMultiplier); const gained = Math.max(0, Math.min(requested, cap - nonNegative(currentShield, 'currentShield'))); return freeze({ cap, requested, gained, shieldAfter: currentShield + gained }); }
  function initialShieldFromSets(combat) { const baseShield = combat.maxHp * (combat.conditional.lifeInitialShieldBp / BP); return applyNumericShield({ baseShield, maxHp: combat.maxHp, sourceMultiplier: combat.shieldMultiplier, targetMultiplier: combat.receivedShieldMultiplier }); }
  function knockbackPolicy({ hitKind, baseKnockback = 0, knockbackPowerBp = 0, knockbackResistanceBp = 0 }) { nonNegative(baseKnockback, 'baseKnockback'); integer(knockbackPowerBp, 'knockbackPowerBp'); integer(knockbackResistanceBp, 'knockbackResistanceBp'); const resistanceMultiplier = 1 / (1 + (knockbackResistanceBp / BP)); const powerMultiplier = multiplier(knockbackPowerBp); if (hitKind === 'direct_hit') return freeze({ mode: 'direct_popup', horizontalMultiplier: 1 + ((knockbackPowerBp / BP) * 0.25), verticalMultiplier: powerMultiplier, resistanceMultiplier, finalKnockback: baseKnockback * powerMultiplier * resistanceMultiplier, additionalNormalProjectileKnockback: knockbackPowerBp === 0 ? 0 : baseKnockback * (powerMultiplier - 1) * resistanceMultiplier }); if (hitKind === 'blast_only') return freeze({ mode: 'radial', horizontalMultiplier: powerMultiplier, verticalMultiplier: powerMultiplier, resistanceMultiplier, finalKnockback: baseKnockback * powerMultiplier * resistanceMultiplier, additionalNormalProjectileKnockback: knockbackPowerBp === 0 ? 0 : baseKnockback * (powerMultiplier - 1) * resistanceMultiplier }); if (hitKind === 'existing_knockback') return freeze({ mode: 'existing_knockback', horizontalMultiplier: powerMultiplier, verticalMultiplier: powerMultiplier, resistanceMultiplier, finalKnockback: baseKnockback * powerMultiplier * resistanceMultiplier, additionalNormalProjectileKnockback: 0 }); fail('INVALID_KNOCKBACK_HIT_KIND', 'hitKind is invalid'); }
  function createRuntimeEffectsState() { return freeze({ rescueNextAttackDamageBp: 0, lastStandNextAttackDamageBp: 0 }); }
  function runtimeState(state) { const value = state || createRuntimeEffectsState(); if (!value || typeof value !== 'object' || Array.isArray(value) || Object.keys(value).sort().join(',') !== 'lastStandNextAttackDamageBp,rescueNextAttackDamageBp' || !Number.isSafeInteger(value.rescueNextAttackDamageBp) || !Number.isSafeInteger(value.lastStandNextAttackDamageBp) || value.rescueNextAttackDamageBp < 0 || value.lastStandNextAttackDamageBp < 0) fail('INVALID_RUNTIME_EFFECTS_STATE'); return clone(value); }
  function resolveRuntimeEffects({ combat, state = createRuntimeEffectsState(), currentHp, actualEnemyDamage = 0, damageType = null }) { nonNegative(currentHp, 'currentHp'); nonNegative(actualEnemyDamage, 'actualEnemyDamage'); const next = runtimeState(state); const lowHp = currentHp <= (combat.maxHp * 0.5); const lowHpAttackBp = combat.conditional.lastStand2 && lowHp ? 1000 : 0;
    if (actualEnemyDamage > 0 && damageType === null) fail('INVALID_DAMAGE_TYPE', 'enemy damage requires a damage type');
    if (actualEnemyDamage > 0 && damageType !== null) assertDamageType(damageType);
    // Any enemy attack source can trigger last stand; environmental/self/fixed cannot.
    if (combat.conditional.lastStand4 && actualEnemyDamage > 0 && ['direct_projectile', 'normal_blast'].includes(damageType)) next.lastStandNextAttackDamageBp = lowHp ? 1500 : 1000;
    const nextAttackDamageBp = next.rescueNextAttackDamageBp + next.lastStandNextAttackDamageBp; return freeze({ state: freeze(next), lowHpAttackBp, nextAttackDamageBp }); }
  // sourceCombat belongs to the supporting unit; targetState belongs to the
  // recipient. Keeping them explicit prevents a target's own set from
  // incorrectly authorizing a rescue buff.
  function recordSupportEvent({ sourceCombat, targetState = createRuntimeEffectsState(), sourceUnitId, targetUnitId, actualHealing = 0, actualShield = 0 }) { if (!sourceCombat || !sourceCombat.conditional || typeof sourceUnitId !== 'string' || !sourceUnitId || typeof targetUnitId !== 'string' || !targetUnitId) fail('INVALID_RECOVERY_EVENT'); nonNegative(actualHealing, 'actualHealing'); nonNegative(actualShield, 'actualShield'); const next = runtimeState(targetState); if (sourceCombat.conditional.rescue4 && sourceUnitId !== targetUnitId && (actualHealing > 0 || actualShield > 0)) next.rescueNextAttackDamageBp = 1000; return freeze({ state: freeze(next), grantedNextAttackDamageBp: next.rescueNextAttackDamageBp }); }
  function beginAttackAction(state) { const checked = runtimeState(state); return freeze({ actionDamageBp: checked.rescueNextAttackDamageBp + checked.lastStandNextAttackDamageBp, state: freeze(checked) }); }
  function completeAttackAction(state) { runtimeState(state); return createRuntimeEffectsState(); }
  function consumeAttackRuntimeEffects(state) { const action = beginAttackAction(state); return freeze({ appliedDamageBp: action.actionDamageBp, nextState: completeAttackAction(action.state) }); }
  return freeze({ GEAR_COMBAT_VERSION: 1, BASE_ATTACK, BASE_DEFENSE, BASE_CRIT_DAMAGE_BP, SHIELD_CAP_BP, DAMAGE_TYPES, calculateGearCombat, calculateBattleGearCombat, calculateDamagePipeline, isCritEligibleDamageType, conditionalDamageModifiers, statusSuccessChance, finalHealing, finalShieldGain, applyNumericShield, initialShieldFromSets, knockbackPolicy, createRuntimeEffectsState, resolveRuntimeEffects, recordSupportEvent, beginAttackAction, completeAttackAction, consumeAttackRuntimeEffects });
});
